import {VERSION,SIGILS,LORE_CATALOG,LORE_LINKS,LORE_TARGETS,ENDING_PROFILES,ROOMS,ENEMY_TYPES,SLICE_ACHIEVEMENTS,bestiaryRank} from './data.js';
import {defaultSave,createNewGamePlus,loadSlot,saveSlot,clearSlot,getSlotSummary,getActiveSlot,setActiveSlot,parseSettings,saveSettings,recoverSlot} from './save.js';
import {AudioSystem} from './audio.js';
import {BlackthornEngine} from './engine.js';
import {sigilById,sigilLabel,sigilStats} from './sigils.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={view:'title',slot:getActiveSlot(),save:null,engine:null,settings:{musicVolume:.35,fxVolume:.65,mute:false,perceptionFx:1,truthfulHud:false,reduceMotion:false,disableShake:false,highContrast:false,textSize:1,touchMode:'always',touchSize:'standard',leftHanded:false,performanceMode:'auto',orientationHint:true,...parseSettings()},audio:null};
state.audio=new AudioSystem(state.settings);
window.__BT404__=state;

function applySettings(){document.documentElement.style.setProperty('--scale',String(state.settings.textSize||1));const b=document.body;b.classList.toggle('high-contrast',!!state.settings.highContrast);b.classList.toggle('reduce-motion',!!state.settings.reduceMotion);b.classList.toggle('left-handed',!!state.settings.leftHanded);b.classList.toggle('touch-large',state.settings.touchSize==='large');b.classList.toggle('touch-hidden',state.settings.touchMode==='hidden');b.classList.toggle('touch-auto',state.settings.touchMode==='auto');const autoBattery=state.settings.performanceMode==='auto'&&matchMedia('(pointer:coarse)').matches&&innerWidth<700;b.classList.toggle('perf-battery',state.settings.performanceMode==='battery'||autoBattery);b.classList.toggle('perf-quality',state.settings.performanceMode==='quality');state.audio.setSettings(state.settings);if(state.engine)state.engine.settings=state.settings;updateViewportState();}
function persistSettings(){saveSettings(state.settings);applySettings();}
function showView(name){state.view=name;for(const v of $$('.view'))v.classList.add('hidden');$(`#${name}View`)?.classList.remove('hidden');if(name==='title')refreshNgPlusButton();updateViewportState();}
let deferredInstallPrompt=null,pwaToastTimer=0,orientationHintTimer=0,orientationHintShown=false;
function updateViewportState(){const vv=window.visualViewport;document.documentElement.style.setProperty('--app-height',`${Math.round(vv?.height||window.innerHeight)}px`);const coarse=matchMedia('(pointer:coarse)').matches,portrait=window.innerHeight>=window.innerWidth;document.body.classList.toggle('is-coarse',coarse);document.body.classList.toggle('is-portrait',portrait);const hint=$('#orientationHint'),should=state.view==='game'&&coarse&&portrait&&state.settings.orientationHint;if(hint){if(should&&!orientationHintShown){orientationHintShown=true;hint.classList.remove('hidden');clearTimeout(orientationHintTimer);orientationHintTimer=setTimeout(()=>hint.classList.add('hidden'),3200);}else if(!should)hint.classList.add('hidden');}}
function standaloneMode(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
function updatePwaStatus(label){const el=$('#pwaStatus');if(!el)return;const offline=!navigator.onLine,installed=standaloneMode();el.textContent=label||(offline?'OFFLINE':installed?'APP':'WEB');el.classList.toggle('offline',offline);el.classList.toggle('ready',installed||el.dataset.offlineReady==='true');}
function toast(text,ms=2600){const el=$('#pwaToast');if(!el)return;clearTimeout(pwaToastTimer);el.textContent=text;el.classList.remove('hidden');pwaToastTimer=setTimeout(()=>el.classList.add('hidden'),ms);}
function updateFullscreenLabel(){const btn=$('#fullscreenBtn');if(!btn)return;const active=!!document.fullscreenElement||document.body.classList.contains('focus-mode');btn.textContent=active?'✕ EXIT':'⛶ FULL';btn.setAttribute('aria-pressed',String(active));}
async function toggleFullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();return;}if(document.body.classList.contains('focus-mode')){document.body.classList.remove('focus-mode');updateFullscreenLabel();updateViewportState();return;}const shell=$('#gameShell');if(shell?.requestFullscreen){await shell.requestFullscreen({navigationUI:'hide'});return;}}catch{}document.body.classList.toggle('focus-mode');updateFullscreenLabel();updateViewportState();if(document.body.classList.contains('focus-mode'))$('#gameShell')?.scrollIntoView({block:'center'});}
async function installApp(){if(deferredInstallPrompt){const prompt=deferredInstallPrompt;deferredInstallPrompt=null;await prompt.prompt();const choice=await prompt.userChoice;$('#installBtn')?.classList.add('hidden');toast(choice.outcome==='accepted'?'Blackthorn 404 added to your device.':'Install dismissed.');return;}if(standaloneMode()){toast('Blackthorn 404 is already running as an installed app.');return;}toast('Install from your browser menu: Add to Home Screen / Install app.',4200);}
function fmtTime(s){const m=Math.floor((s||0)/60);const sec=Math.floor((s||0)%60);return `${m}:${String(sec).padStart(2,'0')}`;}

function slotHeadline(sum){if(sum.empty)return 'EMPTY MEMORY';const end=sum.ending==='true'?'TRUE ENDING · NO ONE REMEMBERS ALONE':sum.ending==='dark'?'DARK ENDING · THE NINTH TENANT':'NORMAL ENDING · HOUSE OF WITNESSES';if(sum.phase12)return `${sum.ngPlus?`NG+${sum.ngPlusCycle} · `:''}${end}`;if(sum.ngPlus)return `NG+${sum.ngPlusCycle} · ${sum.phase9?'THE ROOM BEHIND MEMORY COMPLETE':sum.phase8?'ALL EIGHT SPINES REMEMBERED':sum.phase7?'CHAPTERS I–IV REMEMBERED':sum.phase6?'SAINT ORREN REMEMBERED':'MEMORY ACTIVE'}`;return sum.phase9?'THE ROOM BEHIND MEMORY COMPLETE':sum.phase8?'ALL EIGHT SPINES REMEMBERED':sum.phase7?'CHAPTERS I–IV REMEMBERED':sum.phase6?'SAINT ORREN REMEMBERED':sum.phase5?'SIGIL GRAMMAR CALIBRATED':sum.phase4?'COMBAT CALIBRATED':sum.phase3?'PERCEPTION CALIBRATED':sum.phase2?'MANOR INDEXED':sum.complete?'MEMORY I COMPLETE':'MEMORY ACTIVE';}
function refreshNgPlusButton(){const b=$('#newGamePlusBtn');if(!b)return;const available=[1,2,3].some(n=>{const s=getSlotSummary(n);return !s.empty&&s.phase12;});b.disabled=!available;b.title=available?'Begin another cycle from a completed slot.':'Complete any ending to unlock New Game+.';}
function renderSlots(mode='load'){const grid=$('#slotGrid');grid.innerHTML='';for(let n=1;n<=3;n++){const sum=getSlotSummary(n),card=document.createElement('button'),eligible=mode!=='ngplus'||(!sum.empty&&sum.phase12);card.className='slot-card'+(mode==='ngplus'&&!eligible?' locked':'');card.type='button';card.dataset.slot=String(n);card.disabled=!eligible;const total=(sum.playSeconds||0)+(sum.legacyPlaySeconds||0),cycle=sum.ngPlus?` · NG+ CYCLE ${sum.ngPlusCycle}`:'';card.innerHTML=sum.empty?`<span class="slot-no">SLOT ${n}</span><b>${mode==='ngplus'?'NG+ LOCKED':'EMPTY MEMORY'}</b><small>${mode==='ngplus'?'Finish an ending in this slot first.':'Begin at Blackthorn Manor · 2026'}</small>`:`<span class="slot-no">SLOT ${n}${cycle}</span><b>${slotHeadline(sum)}</b><small>${esc(sum.room.replaceAll('-',' ').toUpperCase())}<br>${fmtTime(total)} total memory${sum.endingsSeen?.length?` · ${sum.endingsSeen.length}/3 endings seen`:''}${sum.ngPlusEchoes?.length?` · ${sum.ngPlusEchoes.length}/9 refracted`:''}</small><span class="delete-slot" data-delete="${n}">DELETE LOCAL SAVE</span>`;card.addEventListener('click',e=>{if(e.target?.dataset?.delete){e.stopPropagation();if(confirm(`Delete slot ${n}? A local backup will also be removed.`)){clearSlot(n);renderSlots(mode);refreshNgPlusButton();}return;}state.slot=setActiveSlot(n);if(mode==='new'){state.save=defaultSave();state.save=saveSlot(n,state.save);launchGame(true);}else if(mode==='ngplus'){const source=loadSlot(n),next=createNewGamePlus(source);if(!next)return;state.save=saveSlot(n,next);launchGame(false);}else{state.save=loadSlot(n);launchGame(false);}});grid.append(card);}}

function openSlots(mode){renderSlots(mode);$('#slotsTitle').textContent=mode==='new'?'Choose a slot for a new memory':mode==='ngplus'?'Choose a completed memory for New Game+':'Choose a save slot';$('#slotGrid').dataset.mode=mode;showView('slots');}
function launchGame(fresh=false){if(state.engine)state.engine.stop();state.save=fresh?saveSlot(state.slot,state.save||defaultSave()):loadSlot(state.slot);showView('game');state.engine=new BlackthornEngine($('#gameCanvas'),{save:state.save,setSave:(s,reason)=>{const saved=saveSlot(state.slot,s);Object.assign(s,saved);state.save=s;},onHud:updateHud,onMessage:openMessage,onPause:openPause,onComplete:(phase)=>showComplete(phase),onSigils:openSigilCodex,onEnding:showEnding,sound:state.audio,settings:state.settings});state.engine.start();state.audio.ensure();state.audio.startAmbient();}

function updateHud(h){
  const pct=v=>`${Math.max(0,Math.min(100,v))}%`;$('#healthBar').style.width=pct(h.health);$('#perceptionBar').style.width=pct(h.perception);$('#stabilityBar').style.width=pct(h.stability);$('#staminaBar').style.width=pct(h.stamina);$('#healthText').textContent=Math.round(h.health);$('#perceptionText').textContent=Math.round(h.perception);$('#stabilityText').textContent=Math.round(h.stability);$('#staminaText').textContent=Math.round(h.stamina);$('#weaponLabel').textContent=h.weapon.name.toUpperCase();$('#sigilLabel').textContent=h.sigilLabel||sigilLabel(h.sigil,h.sigilIntensity||1);$('#roomLabel').textContent=`${h.ngPlus?`NG+${h.ngPlusCycle} · `:''}${String(h.roomName||h.room.name).toUpperCase()} · ${h.room.era}`;
  if($('#combatState')){const ammo=h.ammo;$('#combatState').textContent=h.reloading?`RELOAD ${Math.ceil(h.reloadRemaining*10)/10}s`:h.charging?`HEAVY ${Math.round(h.charge*100)}%`:ammo?`AMMO ${ammo.clip}/${ammo.reserve}`:h.combo>1?`COMBO ×${h.combo}`:'COMBAT READY';}
  const tier=Number.isFinite(h.perceptionTier)?h.perceptionTier:(h.actualPerception>75?0:h.actualPerception>50?1:h.actualPerception>25?2:h.actualPerception>10?3:4);$('#perceptionOverlay').style.opacity=String([0,.06,.14,.24,.36][tier]*(state.settings.perceptionFx??1));$('#gameShell').classList.toggle('hud-unreliable',!!h.unreliable);$('#perceptionState').textContent=h.unreliable?`PERCEPTION ${tier} · HUD UNRELIABLE`:tier?`PERCEPTION ${tier}`:'PERCEPTION STABLE';
  const boss=h.boss;if(boss){$('#bossHud').classList.remove('hidden');$('#bossName').textContent=boss.name.toUpperCase();$('#bossBar').style.width=`${Math.max(0,boss.hp/boss.maxHp*100)}%`;$('#bossPhase').textContent=`PHASE ${['I','II','III'][Math.max(0,(h.phase||1)-1)]}`;}else $('#bossHud').classList.add('hidden');
}

let messageQueue=[],messageDone=null;
function openMessage(lines,done){messageQueue=[...(lines||[])];messageDone=done||null;$('#messageDialog').showModal();advanceMessage();}
function advanceMessage(){if(messageQueue.length){$('#messageLines').innerHTML=`<p>${String(messageQueue.shift()).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}</p>`;$('#messageNextBtn').textContent=messageQueue.length?'CONTINUE · C / ENTER':'RETURN · C / ENTER';state.audio.play('note');return;}$('#messageDialog').close();const cb=messageDone;messageDone=null;cb?.();}
function openPause(paused){if(!paused){if($('#pauseDialog').open)$('#pauseDialog').close();return;}$('#pauseWeapon').textContent=state.engine?.weapon.name||'—';$('#pauseSigil').textContent=state.engine?sigilLabel(sigilById(state.engine.save.equippedSigil),state.engine.save.sigilIntensity||1):'—';$('#pauseRoom').textContent=state.engine?.room().name||'—';$('#pauseNotes').textContent=String(state.engine?.save.lore?.length||0);if(!$('#pauseDialog').open)$('#pauseDialog').showModal();}

let archiveFilter='all',archiveSelected=null,archiveReturn='playing';
const loreKnown=()=>{if(!state.engine)return[];const ids=[...new Set([...(state.engine.save.lore||[]),...(state.engine.save.legacyLore||[])])];return ids.map(id=>LORE_CATALOG[id]).filter(Boolean);};
const esc=t=>String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function renderLoreArchive(){
  const known=loreKnown(),counts={document:0,note:0,recording:0,secret:0},current=new Set(state.engine?.save.lore||[]),legacy=new Set(state.engine?.save.legacyLore||[]);for(const e of known)counts[e.type]=(counts[e.type]||0)+1;
  $('#archiveCount').textContent=state.engine?.save.ngPlus?`CURRENT ${current.size}/${LORE_TARGETS.total} · REMEMBERED ${legacy.size}/${LORE_TARGETS.total} · REFRACTED ${state.engine.save.ngPlusEchoes?.length||0}/9`:`${known.length}/${LORE_TARGETS.total} EVIDENCE · DOC ${counts.document}/${LORE_TARGETS.document} · NOTE ${counts.note}/${LORE_TARGETS.note} · REC ${counts.recording}/${LORE_TARGETS.recording} · SECRET ${counts.secret}/${LORE_TARGETS.secret}`;
  for(const b of $$('#archiveFilters button'))b.classList.toggle('selected',b.dataset.filter===archiveFilter);
  const visible=known.filter(e=>archiveFilter==='all'||e.type===archiveFilter).sort((a,b)=>String(a.era).localeCompare(String(b.era))||a.title.localeCompare(b.title));
  if(!archiveSelected||!visible.some(e=>e.id===archiveSelected))archiveSelected=visible[0]?.id||null;
  const list=$('#archiveList');list.innerHTML='';for(const e of visible){const b=document.createElement('button');b.type='button';b.className='archive-row'+(archiveSelected===e.id?' selected':'');b.innerHTML=`<span>${e.type.toUpperCase()}</span><b>${esc(e.title)}</b><small>${esc(e.era)} · ${esc(e.room)}</small>`;b.addEventListener('click',()=>{archiveSelected=e.id;renderLoreArchive();});list.append(b);}
  const e=archiveSelected?LORE_CATALOG[archiveSelected]:null,detail=$('#archiveDetail');if(!e){detail.innerHTML='<p class="archive-empty">No recovered evidence in this filter.</p>';return;}
  const linked=(LORE_LINKS[e.id]||[]).map(id=>LORE_CATALOG[id]).filter(x=>x&&known.some(k=>k.id===x.id)),isLegacy=state.engine?.save.ngPlus&&!current.has(e.id)&&legacy.has(e.id);
  detail.innerHTML=`${isLegacy?'<p class="archive-legacy">REMEMBERED FROM A PREVIOUS CYCLE · DOES NOT COUNT AS REDISCOVERED EVIDENCE</p>':''}<p class="eyebrow">${e.type.toUpperCase()} · ${esc(e.era)}</p><h2>${esc(e.title)}</h2><p class="archive-source">${esc(e.area)} · ${esc(e.room)}</p><p class="archive-thread">THREAD · ${esc(e.thread)}</p>${e.text.map(x=>`<p>${esc(x)}</p>`).join('')}<p class="archive-annotation">${esc(e.annotation)}</p>${linked.length?`<div class="archive-links"><b>KNOWN CONNECTIONS</b>${linked.map(x=>`<span>${esc(x.era)} · ${esc(x.title)}</span>`).join('')}</div>`:''}`;
}
function openLoreArchive(){if(!state.engine)return;archiveReturn=state.engine.mode==='paused'?'paused':'playing';if($('#pauseDialog').open)$('#pauseDialog').close();if(state.engine.mode==='playing'||state.engine.mode==='paused')state.engine.mode='archive';renderLoreArchive();if(!$('#archiveDialog').open)$('#archiveDialog').showModal();}
function closeLoreArchive(){if($('#archiveDialog').open)$('#archiveDialog').close();if(!state.engine)return;state.engine.mode=archiveReturn;if(archiveReturn==='paused')openPause(true);else state.engine.hud();}



let recordsTab='achievements',recordsReturn='title';
function recordsSave(){return state.engine?.save||loadSlot(state.slot);}
function discoveredBestiary(save){const found=new Set();for(const rid of save.rooms||[]){for(const e of ROOMS[rid]?.enemies||[])found.add(e.type);}for(const id of save.bosses||[])found.add(id);return found;}
function renderRecords(){const save=recordsSave(),list=$('#recordsList');list.innerHTML='';for(const b of $$('#recordsTabs button'))b.classList.toggle('selected',b.dataset.recordTab===recordsTab);if(recordsTab==='achievements'){const unlocked=new Set(save.achievements||[]),visibleUnlocked=SLICE_ACHIEVEMENTS.filter(a=>unlocked.has(a.id)).length;$('#recordsCount').textContent=`${visibleUnlocked}/${SLICE_ACHIEVEMENTS.length} ACHIEVEMENTS`;for(const a of SLICE_ACHIEVEMENTS){const row=document.createElement('article');const yes=unlocked.has(a.id);row.className='record-row '+(yes?'unlocked':'locked');row.innerHTML=`<span>${yes?'RECOVERED':'LOCKED'}</span><div><b>${yes?esc(a.name):'????????'}</b><p>${yes?esc(a.desc):'Continue exploring Blackthorn and its Memory Echoes.'}</p></div>`;list.append(row);}}else{const found=discoveredBestiary(save),ids=Object.keys(ENEMY_TYPES);$('#recordsCount').textContent=`${found.size}/${ids.length} BESTIARY ENTRIES`;for(const id of ids){const e=ENEMY_TYPES[id],yes=found.has(id),row=document.createElement('article');row.className='record-row '+(yes?'unlocked':'locked');row.innerHTML=`<span>${yes?bestiaryRank(id):'UNKNOWN'}</span><div><b>${yes?esc(e.name):'????????'}</b><p>${yes?`${esc(e.family)} · ${esc(e.behavior.toUpperCase())} · HP ${e.hp} · PRESSURE ${e.perception}`:'Encounter this presence to stabilise its record.'}</p></div>`;list.append(row);}}}
function openRecords(){recordsReturn=state.engine?(state.engine.mode==='paused'?'paused':'playing'):'title';if($('#pauseDialog').open)$('#pauseDialog').close();if(state.engine&&(state.engine.mode==='playing'||state.engine.mode==='paused'))state.engine.mode='records';renderRecords();if(!$('#recordsDialog').open)$('#recordsDialog').showModal();}
function closeRecords(){if($('#recordsDialog').open)$('#recordsDialog').close();if(!state.engine)return;if(recordsReturn==='paused'){state.engine.mode='paused';openPause(true);}else{state.engine.mode='playing';state.engine.hud();}}

let endingPages=[],endingPage=0,endingResult=null;
function renderEndingPage(){
  const profile=endingResult?.profile;if(!profile)return;const page=endingPages[endingPage]||[];
  $('#endingDialog').style.setProperty('--ending-accent',profile.accent||'#9f796b');
  $('#endingKicker').textContent=profile.subtitle;$('#endingTitle').textContent=profile.title;
  $('#endingPage').innerHTML=page.map((x,i)=>i===0?`<h3>${esc(x)}</h3>`:`<p>${esc(x)}</p>`).join('');
  $('#endingProgress').textContent=`MEMORY ${endingPage+1} / ${endingPages.length}`;
  $('#endingNextBtn').textContent=endingPage<endingPages.length-1?'CONTINUE':'RETURN TO TITLE';
  const st=endingResult,requirements=$('#endingRequirements');
  if(endingPage===endingPages.length-1){requirements.classList.remove('hidden');requirements.innerHTML=st.id==='true'?`<b>TRUE ENDING CONDITIONS HELD</b><span>${st.secretCount}/15 counter-memories · ${st.keyEvidence}/${st.keyEvidenceTarget} key evidence · 12 Sigils at Intensity III · all three preserving choices</span>`:st.id==='dark'?`<b>THE HOUSE COUNTED ${st.darkSignals}/3 ERASURE SIGNALS</b><span>The ending followed decisions already carried into the final room. No ending was selected here.</span>`:`<b>BLACKTHORN REMAINS AN ARCHIVE</b><span>${st.secretCount}/15 counter-memories · ${st.keyEvidence}/${st.keyEvidenceTarget} key evidence. Another history remains possible in another save.</span>`;}else requirements.classList.add('hidden');
}
function showEnding(result){endingResult=result;endingPages=[...(result.profile?.pages||[])];endingPage=0;if($('#completeDialog').open)$('#completeDialog').close();if($('#pauseDialog').open)$('#pauseDialog').close();renderEndingPage();if(!$('#endingDialog').open)$('#endingDialog').showModal();}
function advanceEnding(){if(!endingResult)return;if(endingPage<endingPages.length-1){endingPage++;state.audio.play('note');renderEndingPage();return;}if($('#endingDialog').open)$('#endingDialog').close();if(state.engine){state.engine.persist('ending-title');state.engine.stop();state.engine=null;}state.audio.stopAmbient();endingResult=null;endingPages=[];endingPage=0;showView('title');}


function showComplete(phase){
  const phase9=phase==='phase9',phase8=phase==='phase8',phase7=phase==='phase7',phase6=phase==='phase6',phase5=phase==='phase5',phase4=phase==='phase4',phase3=phase==='phase3',phase2=phase==='phase2';
  $('#completeKicker').textContent=phase9?'ROOT MEMORY STABILIZED':phase8?'EIGHT MEMORIES RECOVERED':phase7?'FOUR MEMORIES RECOVERED':phase6?'MEMORY I RECOVERED':phase5?'SIGIL GRAMMAR RECOVERED':phase4?'WEAPON IMPRINT STABLE':phase3?'MIRROR CALIBRATED':phase2?'MANOR INDEXED':'MEMORY THREAD STABILIZED';
  $('#completeTitle').textContent=phase9?'The Unremembered has been made local.':phase8?'All eight Memory Spines are awake.':phase7?'The house now remembers four centuries.':phase6?'Saint Orren remembers twenty-one names.':phase5?'The house now has a grammar.':phase4?'Elena can read the instant before impact.':phase3?'The mirror can no longer pretend to be neutral.':phase2?'Blackthorn is an index.':'The house remembers Ysabel.';
  $('#completeText').textContent=phase9?'Elena crossed the Root Door, reconstructed the three final relations, used all three Sigil schools under altered Perception and defeated The Unremembered without collapsing the eight recovered lives into one official story. Her carried choices remain unresolved.':phase8?'Eleanor Blackthorn, Elias Ward, Naomi Pike and Theo Voss are fully recovered. All eight historical Memory Spines now converge on the Root Door.':phase7?'Nara Kesh, Marcus Aelian and Lucia Varetti are fully recovered. Their contradictions now coexist inside Blackthorn without being forced into one account.':phase6?'Ysabel Thorne’s memory holds together at last. Twenty-one names survive the Bell, the plague ward and the route beneath Saint Orren.':phase5?'Twelve formulas now share one grammar: Verb + School + Intensity. FLESH, MIND and VOID can press against body, attention and boundary without becoming interchangeable.':phase4?'Distance, commitment, recoil and the instant before impact have become readable memories. Blackthorn can now reconstruct violence without turning Elena into a soldier.':phase3?'Four levels of altered perception can now be recognised for what they are: pressure on attention, architecture and interpretation — never changes to the world outside the game.':phase2?'The estate plan, internal routes, safe room, family archive and Memory Vault now form a coherent map of the impossible house.':'The first Memory Echo is stable. Blackthorn Manor has opened new routes in response.';
  $('#completeCloseBtn').textContent=phase9?'RETURN TO ROOT DOOR':phase8?'RETURN TO ROOT DOOR':phase7?'RETURN TO MEMORY VAULT':phase6?'RETURN TO BLACKTHORN MANOR':phase5||phase4?'RETURN TO MEMORY VAULT':phase3?'RETURN TO MIRROR ROOM':phase2?'RETURN TO MEMORY VAULT':'EXPLORE THE MANOR';
  if(!$('#completeDialog').open)$('#completeDialog').showModal();
}

function renderSigilCodex(){
  const e=state.engine;if(!e)return;const grid=$('#sigilGrid');grid.innerHTML='';for(const school of ['FLESH','MIND','VOID']){const section=document.createElement('section');section.className=`sigil-school ${school.toLowerCase()}`;section.innerHTML=`<h3>${school}</h3>`;for(const s of SIGILS.filter(x=>x.school===school&&e.save.sigils.includes(x.id))){const b=document.createElement('button');b.type='button';b.className='sigil-card'+(e.save.equippedSigil===s.id?' selected':'');b.dataset.sigilId=s.id;b.innerHTML=`<b>${s.verb}</b><span>${s.school}</span><small>${s.desc}</small>`;b.addEventListener('click',()=>{e.equipSigil(s.id);renderSigilCodex();});section.append(b);}grid.append(section);}
  const intensity=e.save.sigilIntensity||1,max=e.save.sigilMaxIntensity||1,selected=sigilById(e.save.equippedSigil),stats=sigilStats(selected,intensity);$('#sigilSelected').textContent=sigilLabel(selected,intensity);$('#sigilMeta').textContent=`${selected.school} · STABILITY ${stats.cost} · COOLDOWN ${stats.cooldown.toFixed(1)}s`;for(const b of $$('#sigilIntensity button')){const n=Number(b.dataset.intensity);b.disabled=n>max;b.classList.toggle('selected',n===intensity);}
}
function openSigilCodex(){const e=state.engine;if(!e||e.mode!=='playing')return;e.mode='sigils';renderSigilCodex();if(!$('#sigilDialog').open)$('#sigilDialog').showModal();}
function closeSigilCodex(){if($('#sigilDialog').open)$('#sigilDialog').close();if(state.engine?.mode==='sigils'){state.engine.mode='playing';state.engine.hud();}}

function leaveGame(){if(state.engine){state.engine.persist('leave');state.engine.stop();state.engine=null;}state.audio.stopAmbient();showView('title');}
function openSettings(){const s=state.settings;$('#musicVolume').value=Math.round((s.musicVolume??.35)*100);$('#fxVolume').value=Math.round((s.fxVolume??.65)*100);$('#perceptionFx').value=String(s.perceptionFx??1);$('#truthfulHud').checked=!!s.truthfulHud;$('#reduceMotion').checked=!!s.reduceMotion;$('#disableShake').checked=!!s.disableShake;$('#highContrast').checked=!!s.highContrast;$('#textSize').value=String(s.textSize??1);$('#touchMode').value=s.touchMode||'always';$('#touchSize').value=s.touchSize||'standard';$('#leftHanded').checked=!!s.leftHanded;$('#performanceMode').value=s.performanceMode||'auto';$('#orientationHintSetting').checked=s.orientationHint!==false;$('#mute').checked=!!s.mute;if(!$('#settingsDialog').open)$('#settingsDialog').showModal();}
function bindSettings(){const bind=(id,key,fn=v=>v)=>{$(id).addEventListener('change',e=>{state.settings[key]=fn(e.target.type==='checkbox'?e.target.checked:e.target.value);persistSettings();});};bind('#musicVolume','musicVolume',v=>Number(v)/100);bind('#fxVolume','fxVolume',v=>Number(v)/100);bind('#perceptionFx','perceptionFx',Number);bind('#truthfulHud','truthfulHud',Boolean);bind('#reduceMotion','reduceMotion',Boolean);bind('#disableShake','disableShake',Boolean);bind('#highContrast','highContrast',Boolean);bind('#textSize','textSize',Number);bind('#touchMode','touchMode',String);bind('#touchSize','touchSize',String);bind('#leftHanded','leftHanded',Boolean);bind('#performanceMode','performanceMode',String);bind('#orientationHintSetting','orientationHint',Boolean);bind('#mute','mute',Boolean);}

function bind(){
  $('#endingDialog').addEventListener('cancel',e=>e.preventDefault());$('#endingNextBtn').addEventListener('click',advanceEnding);
  $('#recordsCloseBtn').addEventListener('click',closeRecords);for(const b of $$('#recordsTabs button'))b.addEventListener('click',()=>{recordsTab=b.dataset.recordTab||'achievements';renderRecords();});$('#recordsBtn').addEventListener('click',openRecords);$('#pauseRecordsBtn').addEventListener('click',openRecords);$('#creditsBtn').addEventListener('click',()=>$('#creditsDialog').showModal());$('#archiveCloseBtn').addEventListener('click',closeLoreArchive);$('#pauseArchiveBtn').addEventListener('click',openLoreArchive);for(const b of $$('#archiveFilters button'))b.addEventListener('click',()=>{archiveFilter=b.dataset.filter||'all';archiveSelected=null;renderLoreArchive();});
  $('#sigilCloseBtn').addEventListener('click',closeSigilCodex);for(const b of $$('#sigilIntensity button'))b.addEventListener('click',()=>{if(!state.engine)return;state.engine.save.sigilIntensity=Math.max(1,Math.min(state.engine.save.sigilMaxIntensity||1,Number(b.dataset.intensity)||1));state.engine.persist('sigil-intensity');renderSigilCodex();});
  $('#homeBtn').addEventListener('click',leaveGame);$('#newGameBtn').addEventListener('click',()=>openSlots('new'));$('#newGamePlusBtn').addEventListener('click',()=>openSlots('ngplus'));$('#continueBtn').addEventListener('click',()=>openSlots('load'));$('#slotsBackBtn').addEventListener('click',()=>showView('title'));$('#leaveBtn').addEventListener('click',leaveGame);$('#helpBtn').addEventListener('click',()=>$('#helpDialog').showModal());$('#settingsBtn').addEventListener('click',openSettings);$('#pauseSettingsBtn').addEventListener('click',()=>{if($('#pauseDialog').open)$('#pauseDialog').close();openSettings();});$('#resumeBtn').addEventListener('click',()=>state.engine?.togglePause());$('#messageNextBtn').addEventListener('click',advanceMessage);$('#completeCloseBtn').addEventListener('click',()=>$('#completeDialog').close());
  $('#fullscreenBtn').addEventListener('click',toggleFullscreen);$('#installBtn').addEventListener('click',installApp);
  bindSettings();
  window.addEventListener('keydown',e=>{if($('#endingDialog').open){e.preventDefault();if(e.code==='Enter'||e.code==='KeyC'||e.code==='Space')advanceEnding();return;}if($('#recordsDialog').open&&(e.code==='Escape'||e.code==='KeyK')){e.preventDefault();closeRecords();return;}if(state.view==='game'&&state.engine&&e.code==='KeyK'&&!$('#messageDialog').open&&!$('#sigilDialog').open&&!$('#archiveDialog').open){e.preventDefault();openRecords();return;}if($('#archiveDialog').open&&(e.code==='Escape'||e.code==='KeyJ')){e.preventDefault();closeLoreArchive();return;}if(state.view==='game'&&state.engine&&e.code==='KeyJ'&&!$('#messageDialog').open&&!$('#sigilDialog').open){e.preventDefault();openLoreArchive();return;}if($('#sigilDialog').open&&(e.code==='Escape'||e.code==='KeyF')){e.preventDefault();closeSigilCodex();return;}if($('#messageDialog').open&&(e.code==='Enter'||e.code==='KeyC'||e.code==='Space')){e.preventDefault();advanceMessage();return;}if($('#pauseDialog').open&&e.code==='Escape'){e.preventDefault();state.engine?.togglePause();return;}if(state.view!=='game'||!state.engine)return;const used=state.engine.setKey(e.code,true);if(used||['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();});
  window.addEventListener('keyup',e=>{state.engine?.setKey(e.code,false);state.engine?.releaseKey(e.code);});
  for(const btn of $$('[data-control]')){const name=btn.dataset.control;const down=e=>{e.preventDefault();state.audio.ensure();try{btn.setPointerCapture(e.pointerId);}catch{}state.engine?.setControl(name,true);};const up=e=>{e.preventDefault();state.engine?.setControl(name,false);};btn.addEventListener('pointerdown',down);btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);btn.addEventListener('contextmenu',e=>e.preventDefault());}
  window.addEventListener('resize',updateViewportState,{passive:true});window.visualViewport?.addEventListener('resize',updateViewportState,{passive:true});window.addEventListener('orientationchange',()=>setTimeout(updateViewportState,80),{passive:true});document.addEventListener('fullscreenchange',()=>{document.body.classList.remove('focus-mode');updateFullscreenLabel();updateViewportState();});window.addEventListener('online',()=>{updatePwaStatus();toast('Connection restored.');});window.addEventListener('offline',()=>{updatePwaStatus();toast('Offline mode. Cached game files remain available.');});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').classList.remove('hidden');updatePwaStatus('INSTALLABLE');});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;$('#installBtn').classList.add('hidden');updatePwaStatus('APP');toast('Blackthorn 404 installed.');});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.engine?.mode==='playing')state.engine.togglePause();});
}

async function registerSW(){updatePwaStatus();if(location.protocol==='file:'||!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});const ready=await navigator.serviceWorker.ready;const status=$('#pwaStatus');if(status){status.dataset.offlineReady='true';updatePwaStatus(navigator.onLine?(standaloneMode()?'APP · OFFLINE READY':'OFFLINE READY'):'OFFLINE');}if(reg.waiting)toast('A newer Blackthorn shell is ready. Reload to update.',4200);reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)toast('Update cached. Reload when convenient.',4200);});});await reg.update();return ready;}catch(err){console.warn('Service Worker unavailable',err);updatePwaStatus('WEB');}}

applySettings();bind();refreshNgPlusButton();updateFullscreenLabel();updatePwaStatus();registerSW();
