import {INTERNAL_W,INTERNAL_H,ROOMS,ENEMY_TYPES,WEAPONS,MANOR_FLOORS,BOSS_PROFILES,LORE_CATALOG,NGPLUS_ECHOES,NGPLUS_ECHO_TARGET,evaluateEnding,BALANCE} from './data.js';
import {PerceptionSystem} from './perception.js';
import {overlaps,attackBox,damageActor,phaseForBoss,clamp} from './combat.js';
import {cycleSigil,cycleIntensity,castSigil,sigilById,sigilLabel} from './sigils.js';

const dist=(a,b)=>Math.hypot((a.x+a.w/2)-(b.x+b.w/2),(a.y+a.h/2)-(b.y+b.h/2));
const seeded=(n)=>{const x=Math.sin(n*999.1)*43758.5453;return x-Math.floor(x)};
const hasAll=(arr,flags)=>!arr||arr.every(f=>flags.includes(f));

export class BlackthornEngine{
  constructor(canvas,{save,setSave,onHud,onMessage,onPause,onComplete,onSigils,onEnding,sound,settings}){
    this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.ctx.imageSmoothingEnabled=false;
    this.save=save;this.setSave=setSave;this.onHud=onHud;this.onMessage=onMessage;this.onPause=onPause;this.onComplete=onComplete;this.onSigils=onSigils;this.onEnding=onEnding;this.sound=sound;this.settings=settings||{};
    this.perceptionSystem=new PerceptionSystem();this.keys=new Set();this.touch=new Set();this.running=false;this.mode='playing';this.last=0;
    this.attackCd=0;this.heavyCd=0;this.parryTimer=0;this.staminaRegenDelay=0;this.noisePulse=0;this.guard=false;this.dodgeTimer=0;this.invuln=0;this.charging=false;this.chargeTime=0;this.reloadTimer=0;this.reloadWeapon=null;this.combo=0;this.comboTimer=0;this.hitStop=0;this.sigilCooldown=0;this.sigilFlash=0;this.sigilBuffs={ward:0,reveal:0,fortify:0,purge:0};this.bossVulnerable=0;this.bossAttackTimer=1.4;this.bossPhase=1;this.roomTime=0;this.screenShake=0;
    this.particles=[];this.projectiles=[];this.phantoms=[];this.echoes=[];this.fakeGlitches=[];this.sceneImages=this.loadSceneImages();this.loadRoom(this.save.room||'manor-vestibule',true);
  }

  loadSceneImages(){
    const paths={
      manor:'assets/art/scene_manor.png',
      medieval:'assets/art/scene_medieval.png',
      ancient:'assets/art/scene_ancient.png',
      modern:'assets/art/scene_modern.png',
      boss:'assets/art/scene_boss.png',
      void:'assets/art/scene_void.png',
    };
    const images={};
    for(const [k,src] of Object.entries(paths)){const im=new Image();im.src=src;images[k]=im;}
    return images;
  }

  sceneKey(room){if(room.id?.startsWith('final-'))return 'void';if(room.boss)return 'boss';if(room.tone==='manor'||room.era==='1790')return 'manor';if(['1198 BCE','395'].includes(room.era))return 'ancient';if(['1917','1956','1987'].includes(room.era))return 'modern';return 'medieval';}
  drawSceneBackdrop(c,room){
    const im=this.sceneImages?.[this.sceneKey(room)];c.fillStyle='#050507';c.fillRect(0,0,INTERNAL_W,INTERNAL_H);
    if(im?.complete&&im.naturalWidth){c.save();c.globalAlpha=room.boss?.58:.44;c.drawImage(im,0,0,INTERNAL_W,INTERNAL_H);c.restore();}
    const horizon=72;c.fillStyle='rgba(4,4,7,.48)';c.fillRect(0,horizon,INTERNAL_W,INTERNAL_H-horizon);const g=c.createLinearGradient(0,horizon,0,INTERNAL_H);g.addColorStop(0,'rgba(13,12,15,.18)');g.addColorStop(1,'rgba(2,2,4,.88)');c.fillStyle=g;c.fillRect(0,horizon,INTERNAL_W,INTERNAL_H-horizon);
    c.save();c.globalAlpha=.22;c.strokeStyle='#7b695f';for(let y=82;y<180;y+=12){c.beginPath();c.moveTo(16,y);c.lineTo(304,y);c.stroke();}for(let x=20;x<304;x+=20){c.beginPath();c.moveTo(160+(x-160)*.22,72);c.lineTo(x,180);c.stroke();}c.restore();
  }

  start(){if(this.running)return;this.running=true;this.last=performance.now();requestAnimationFrame(this.loop);if(this.save.ngPlus&&!this.save.flags.includes('ngplus:intro-seen'))this.scheduleNgPlusIntro();}
  scheduleNgPlusIntro(){const tryOpen=()=>{if(!this.running||this.save.flags.includes('ngplus:intro-seen'))return;if(this.mode!=='playing'){setTimeout(tryOpen,90);return;}this.addFlag('ngplus:intro-seen');this.persist('ngplus-intro');const source=(this.save.ngPlusSourceEnding||'unknown').toUpperCase();const trait=(this.save.ngPlusTrait||'memory').replaceAll('-',' ').toUpperCase();this.message([`NEW GAME+ · CYCLE ${this.save.ngPlusCycle}`,`Previous ending: ${source}. Legacy: ${trait}.`,'Campaign doors, bosses and chapter progress have reset. Endings, achievements and remembered evidence remain in meta-memory.','Some rooms now contain Refracted Memories that did not exist on the first reading.']);};setTimeout(tryOpen,160);}
  stop(){this.running=false;}
  loop=(now)=>{if(!this.running)return;const dt=Math.min(.034,Math.max(.001,(now-this.last)/1000||.016));this.last=now;if(this.mode==='playing')this.update(dt);this.render();requestAnimationFrame(this.loop);}
  get weapon(){return WEAPONS.find(w=>w.id===this.save.weapon)||WEAPONS[0];}
  resolveRoomId(id){if(id==='manor-gallery'&&this.save.sliceComplete)return 'manor-gallery-after';return id;}
  room(){return ROOMS[this.resolveRoomId(this.save.room)]||ROOMS['manor-vestibule'];}
  persist(reason='autosave'){this.save.health=this.player?.hp??this.save.health;this.save.updatedAt=Date.now();this.setSave(this.save,reason);this.hud();}
  hud(){const room=this.room(),actual={health:this.player?.hp??this.save.health,perception:this.save.perception,stability:this.save.stability,stamina:this.save.stamina},fx=this.perceptionSystem.fx(this.save.perception,this.settings),view=this.perceptionSystem.hudView(actual,room,fx,this.roomTime),ammo=this.ammoFor(this.weapon);const sigil=sigilById(this.save.equippedSigil),sigilIntensity=this.save.sigilIntensity||1;this.onHud?.({health:view.health,perception:view.perception,stability:view.stability,stamina:view.stamina,actualHealth:actual.health,actualPerception:actual.perception,actualStability:actual.stability,actualStamina:actual.stamina,unreliable:view.unreliable,perceptionTier:fx.tier,weapon:this.weapon,ammo,sigil,sigilLabel:sigilLabel(sigil,sigilIntensity),sigilIntensity,sigilMaxIntensity:this.save.sigilMaxIntensity||1,room,roomName:view.roomName,cooldown:this.sigilCooldown,boss:this.enemies?.find(e=>e.boss&&!e.dead)||null,phase:this.bossPhase,mapUnlocked:this.save.mapUnlocked,phase2Complete:this.save.phase2Complete,phase3Complete:this.save.phase3Complete,phase4Complete:this.save.phase4Complete,phase5Complete:this.save.phase5Complete,charging:this.charging,charge:this.weapon.chargeMax?Math.min(1,this.chargeTime/this.weapon.chargeMax):0,reloading:this.reloadTimer>0,reloadRemaining:this.reloadTimer,combo:this.combo,ngPlus:!!this.save.ngPlus,ngPlusCycle:this.save.ngPlusCycle||0,ngPlusEchoes:this.save.ngPlusEchoes?.length||0});}
  message(lines,after=null){this.mode='dialogue';this.onMessage?.(lines,()=>{this.mode='playing';after?.();this.hud();});}
  unlockAchievement(id){if(!this.save.achievements.includes(id)){this.save.achievements.push(id);this.persist('achievement');}}
  addFlag(flag){if(flag&&!this.save.flags.includes(flag))this.save.flags.push(flag);}
  collectLore(id){if(!id||!LORE_CATALOG[id])return false;if(!Array.isArray(this.save.lore))this.save.lore=[];if(this.save.lore.includes(id))return false;this.save.lore.push(id);if(this.save.lore.length===20)this.unlockAchievement('paper-trail');if(this.save.lore.length===87)this.unlockAchievement('counter-memory');return true;}
  recordPerceptionTier(tier){if(tier<=0)return false;this.save.perceptionMaxTier=Math.max(this.save.perceptionMaxTier||0,tier);if(!this.save.perceptionTiersSeen.includes(tier)){this.save.perceptionTiersSeen.push(tier);this.save.perceptionTiersSeen.sort((a,b)=>a-b);return true;}return false;}
  loadRoom(rawId,heal=false){
    const id=this.resolveRoomId(rawId),room=ROOMS[id]||ROOMS['manor-vestibule'];this.save.previousRoom=this.save.room;this.save.room=id;if(!this.save.rooms.includes(id))this.save.rooms.push(id);
    if(room.weapon)this.save.weapon=room.weapon;if(room.tone==='manor')this.save.manorVisits=(this.save.manorVisits||0)+1;if(this.save.sliceComplete)this.save.houseStage=Math.max(1,this.save.houseStage||0);
    const [sx,sy]=room.spawn||[32,126];this.player={x:sx,y:sy,w:10,h:14,hp:heal?100:Math.max(1,this.save.health||100),facing:'right',speed:58,hitFlash:0};
    this.enemies=(room.enemies||[]).map((spec,i)=>this.spawnEnemy(spec,i));this.projectiles=[];this.particles=[];this.phantoms=[];this.echoes=[];this.fakeGlitches=[];this.roomTime=0;this.attackCd=0;this.heavyCd=0;this.parryTimer=0;this.staminaRegenDelay=0;this.noisePulse=0;this.guard=false;this.dodgeTimer=0;this.charging=false;this.chargeTime=0;this.reloadTimer=0;this.reloadWeapon=null;this.combo=0;this.comboTimer=0;this.hitStop=0;this.bossVulnerable=room.boss?1.8:0;this.bossAttackTimer=1.4;this.bossPhase=1;
    this.save.health=this.player.hp;this.persist('room');this.sound?.setScene?.(room);this.sound?.play('door');
    if(id==='manor-vestibule')this.unlockAchievement('first-step');
    if(room.enter?.length)setTimeout(()=>{if(this.running&&this.save.room===id&&this.mode==='playing')this.message(room.enter);},30);
  }
  spawnEnemy(spec,i){const d=ENEMY_TYPES[spec.type],size=d.size||[12,14],poise=d.poise||16,cycle=this.save.ngPlus?Math.max(1,this.save.ngPlusCycle||1):0,hpScale=cycle?Math.min(BALANCE.ngPlus.hpCap,1+cycle*BALANCE.ngPlus.hpPerCycle):1,damageScale=cycle?Math.min(BALANCE.ngPlus.damageCap,1+cycle*BALANCE.ngPlus.damagePerCycle):1,speedScale=cycle?Math.min(BALANCE.ngPlus.speedCap,1+cycle*BALANCE.ngPlus.speedPerCycle):1,hp=Math.max(1,Math.round(d.hp*hpScale));return {id:`${spec.type}-${i}`,type:spec.type,name:d.name,family:d.family,x:spec.x,y:spec.y,w:size[0],h:size[1],hp,maxHp:hp,speed:d.speed*speedScale,damage:d.damage*damageScale,perception:d.perception,behavior:d.behavior,boss:!!spec.boss,dead:false,hitFlash:0,bound:0,attackCd:.5+seeded(i)*.6,state:0,phase:1,maxPoise:poise,poise,stagger:0,windup:0,windupMax:d.windup||.26,pendingAttack:false,confused:0,branded:0,brandPower:1,bossClock:0,patternIndex:0,lastPlayerX:0,lastPlayerY:0,teleportCd:0};}
  distanceToPlayer(e){return dist(this.player,e);}
  setKey(code,down){
    if(down)this.keys.add(code);else this.keys.delete(code);if(!down)return false;
    if(code==='Escape'){if(this.mode==='map')this.toggleMap();else this.togglePause();return true;}
    if(code==='KeyM'){this.toggleMap();return true;}if(code==='KeyF'){this.onSigils?.();return true;}
    if(this.mode!=='playing')return false;
    if(code==='KeyC'||code==='Enter'){this.interact();return true;}if(code==='KeyZ'){this.quickAttack();return true;}if(code==='KeyV'){this.startHeavyCharge();return true;}if(code==='KeyQ'){this.cycleWeapon(-1);return true;}if(code==='KeyE'){this.cycleWeapon(1);return true;}if(code==='KeyR'){this.cast();return true;}if(code==='KeyT'){this.cycleSigil();return true;}if(code==='KeyG'){this.cycleSigilIntensity();return true;}if(code==='Space'){this.dodge();return true;}if(code==='KeyX'){this.startGuard();return true;}return false;
  }
  releaseKey(code){if(code==='KeyX')this.endGuard();if(code==='KeyV')this.releaseHeavyCharge();}
  setControl(name,down){
    if(down)this.touch.add(name);else this.touch.delete(name);if(!down){if(name==='guard')this.endGuard();if(name==='heavy')this.releaseHeavyCharge();return;}
    if(name==='map'){this.toggleMap();return;}if(name==='sigils'){this.onSigils?.();return;}if(this.mode!=='playing'&&name!=='pause')return;
    if(name==='attack')this.quickAttack();else if(name==='heavy')this.startHeavyCharge();else if(name==='guard')this.startGuard();else if(name==='interact')this.interact();else if(name==='sigil')this.cast();else if(name==='swap')this.cycleSigil();else if(name==='intensity')this.cycleSigilIntensity();else if(name==='weapon')this.cycleWeapon(1);else if(name==='dodge')this.dodge();else if(name==='pause')this.togglePause();
  }
  togglePause(){if(this.mode==='dialogue'||this.mode==='map')return;this.mode=this.mode==='paused'?'playing':'paused';this.onPause?.(this.mode==='paused');this.hud();}
  toggleMap(){
    if(this.mode==='dialogue'||this.mode==='paused')return;
    if(!this.save.mapUnlocked){if(this.mode==='playing')this.message(['NO RELIABLE FLOORPLAN','Blackthorn changes faster than memory. Find a survey of the house first.']);return;}
    this.mode=this.mode==='map'?'playing':'map';this.sound?.play('note');this.hud();
  }
  unlockWeapon(id,persist=true){if(!id)return false;if(!Array.isArray(this.save.weapons))this.save.weapons=[];if(this.save.weapons.includes(id))return false;this.save.weapons.push(id);if(persist)this.persist('weapon-unlock');return true;}
  availableWeapons(){const ids=(this.save.weapons||[]).filter(id=>WEAPONS.some(w=>w.id===id));return ids.length?ids:['candlestick'];}
  ammoFor(w=this.weapon){if(!w?.ammoType)return null;this.save.ammo=this.save.ammo||{};if(!this.save.ammo[w.ammoType])this.save.ammo[w.ammoType]={clip:w.clip||1,reserve:w.reserveStart||0};return this.save.ammo[w.ammoType];}
  cycleWeapon(dir=1){if(this.mode!=='playing')return null;const room=this.room();if(room.weapon&&!room.combatTrial){this.spawnText('FIXED MEMORY',this.player.x-8,this.player.y-5);return this.weapon;}const ids=this.availableWeapons();let i=Math.max(0,ids.indexOf(this.save.weapon));i=(i+(dir<0?-1:1)+ids.length)%ids.length;this.save.weapon=ids[i];this.charging=false;this.chargeTime=0;this.reloadTimer=0;this.reloadWeapon=null;this.sound?.play('note');this.persist('weapon-equip');return this.weapon;}
  startGuard(){if(this.mode!=='playing'||this.guard||this.charging)return;this.guard=true;this.parryTimer=.17+(this.weapon.parryBonus||0);this.sound?.play('note');}
  endGuard(){this.guard=false;this.parryTimer=0;}
  dodge(){if(this.mode!=='playing'||this.save.stamina<BALANCE.stamina.dodgeCost||this.dodgeTimer>0||this.charging)return;this.save.stamina-=BALANCE.stamina.dodgeCost;this.staminaRegenDelay=Math.max(this.staminaRegenDelay,BALANCE.stamina.dodgeDelay);this.dodgeTimer=.28;this.invuln=.32;const v=this.facingVector();this.tryMove(v.x*25,v.y*25);this.spawnBurst(this.player.x+5,this.player.y+8,7);}
  quickAttack(){if(this.mode!=='playing'||this.attackCd>0||this.charging||this.reloadTimer>0)return;const w=this.weapon,cost=w.quickStamina||0;if(this.save.stamina<cost){this.spawnText('TIRED',this.player.x-4,this.player.y-4);return;}if(w.type==='ranged'){this.fireWeapon(false,0);return;}this.save.stamina-=cost;this.staminaRegenDelay=Math.max(this.staminaRegenDelay,BALANCE.stamina.quickDelay);this.attackCd=w.cooldown;this.combo=this.comboTimer>0?Math.min(3,this.combo+1):1;this.comboTimer=.7;const comboScale=1+(this.combo-1)*.08;this.performAttack(w.damage*comboScale,false,w.poise||5,1);}
  startHeavyCharge(){if(this.mode!=='playing'||this.charging||this.heavyCd>0||this.reloadTimer>0||this.save.stamina<this.weapon.stamina)return;this.charging=true;this.chargeTime=0;this.guard=false;this.parryTimer=0;this.sound?.play('note');}
  releaseHeavyCharge(){if(!this.charging)return;const w=this.weapon,p=Math.max(.18,Math.min(1,this.chargeTime/(w.chargeMax||.8)));this.charging=false;this.chargeTime=0;this.heavyAttack(p);}
  heavyAttack(charge=.18){if(this.mode!=='playing'||this.heavyCd>0||this.save.stamina<this.weapon.stamina||this.reloadTimer>0)return;const w=this.weapon,p=Math.max(.18,Math.min(1,charge));this.save.stamina-=w.stamina;this.staminaRegenDelay=Math.max(this.staminaRegenDelay,BALANCE.stamina.heavyDelay);this.heavyCd=.5+(w.cooldown||.3);this.combo=0;this.comboTimer=0;if(w.type==='ranged'){this.fireWeapon(true,p,true);return;}const dmg=w.heavy*(.72+.5*p),poise=(w.heavyPoise||12)*(.75+.55*p);this.performAttack(dmg,true,poise,p);}
  performAttack(amount,heavy,poiseDamage=6,potency=1){
    const box=attackBox(this.player,this.weapon.reach+(heavy?Math.round(4+5*potency):0));let hit=false;for(const e of this.enemies){if(e.dead||!overlaps(box,e))continue;if(e.boss&&!this.bossCanBeHit(e)){this.spawnText('UNFIXED',e.x,e.y);continue;}const v=this.facingVector(),scaled=amount*(e.branded>0?(e.brandPower||1):1);const dead=damageActor(e,scaled,{x:v.x*(heavy?5+5*potency:3),y:v.y*(heavy?5+5*potency:3)});if(e.branded>0)e.branded=Math.max(0,e.branded-(heavy?2.5:1.4));this.applyPoise(e,poiseDamage);e.attackCd=Math.max(e.attackCd,.24);hit=true;this.hitStop=Math.max(this.hitStop,heavy?.055:.028);this.spawnBurst(e.x+e.w/2,e.y+e.h/2,heavy?13:8);if(heavy)this.save.combatStats.heavyHits++;if(dead)this.killEnemy(e);}
    for(const p of this.phantoms){if(p.type!=='enemy'||p.life<=0)continue;const ghost={x:p.x,y:p.y,w:p.w||11,h:p.h||16};if(overlaps(box,ghost)){p.life=0;hit=true;this.spawnText('NOTHING',p.x,p.y-3);this.save.stability=Math.min(100,this.save.stability+2);}}
    this.sound?.play(hit?'hit':'step');if(heavy)this.screenShake=.1+.1*potency;
  }
  applyPoise(e,amount){if(!e||e.dead)return false;e.poise=Math.max(0,(e.poise??e.maxPoise??16)-amount);if(e.poise>0)return false;e.stagger=e.boss?.55:1.0;e.pendingAttack=false;e.windup=0;e.bound=Math.max(e.bound||0,e.boss?.25:.5);e.poise=e.maxPoise||16;this.save.combatStats.staggers++;this.unlockAchievement('break-the-shape');this.spawnText('STAGGER',e.x-5,e.y-4);this.sound?.play('stagger');this.screenShake=Math.max(this.screenShake,.14);return true;}
  fireWeapon(heavy=false,potency=.18,staminaAlreadyPaid=false){const w=this.weapon,ammo=this.ammoFor(w);if(!ammo)return;if(this.reloadTimer>0)return;if(ammo.clip<=0){this.startReload(w);return;}const cost=staminaAlreadyPaid?0:(heavy?w.stamina:(w.quickStamina||0));if(this.save.stamina<cost){this.spawnText('TIRED',this.player.x-4,this.player.y-4);return;}this.save.stamina-=cost;if(cost>0)this.staminaRegenDelay=Math.max(this.staminaRegenDelay,heavy?BALANCE.stamina.heavyDelay:BALANCE.stamina.quickDelay);ammo.clip--;this.attackCd=w.cooldown;const v=this.facingVector(),p=Math.max(.18,Math.min(1,potency)),damage=heavy?w.heavy*(.72+.5*p):w.damage,poise=heavy?(w.heavyPoise||16)*(.75+.55*p):(w.poise||8);this.projectiles.push({x:this.player.x+5+v.x*9,y:this.player.y+7+v.y*9,vx:v.x*w.projectileSpeed,vy:v.y*w.projectileSpeed,r:2,life:1.8,damage,poise,hostile:false,weapon:w.id,heavy});this.sound?.play('shot');this.screenShake=Math.max(this.screenShake,heavy?.11:.045);if(ammo.clip===0&&ammo.reserve<=0)this.spawnText('EMPTY',this.player.x-3,this.player.y-5);}
  startReload(w=this.weapon){const ammo=this.ammoFor(w);if(!ammo||ammo.clip>=w.clip||ammo.reserve<=0||this.reloadTimer>0)return false;this.reloadTimer=w.reload||1;this.reloadWeapon=w.id;this.sound?.play('reload');this.spawnText('RELOAD',this.player.x-5,this.player.y-4);return true;}
  finishReload(){if(!this.reloadWeapon)return;const w=WEAPONS.find(x=>x.id===this.reloadWeapon),ammo=this.ammoFor(w);if(w&&ammo){const need=Math.max(0,w.clip-ammo.clip),take=Math.min(need,ammo.reserve);ammo.clip+=take;ammo.reserve-=take;}this.reloadTimer=0;this.reloadWeapon=null;this.sound?.play('note');}
  killEnemy(e){e.dead=true;this.spawnBurst(e.x+e.w/2,e.y+e.h/2,e.boss?28:15);if(e.boss){this.sound?.play('win');this.completeBoss(e);}else if(this.room().combatTrial&&this.enemies.filter(x=>!x.dead).length===0){this.completeCombatTrial();}else if(this.save.room==='echo-crypt'&&this.enemies.filter(x=>!x.dead&&!x.boss).length===0){this.unlockAchievement('clear-crypt');this.message(['THE CRYPT FALLS QUIET','The eastern threshold unseals.']);}}
  cast(){castSigil(this);}
  cycleSigil(dir=1){const s=cycleSigil(this.save,dir);if(s){this.sound?.play('note');this.persist('equip');return s;}return null;}
  cycleSigilIntensity(dir=1){const i=cycleIntensity(this.save,dir);this.sound?.play('note');this.spawnText(`INTENSITY ${['I','II','III'][i-1]}`,this.player.x-9,this.player.y-5);this.persist('sigil-intensity');return i;}
  equipSigil(id,intensity=null){if(!this.save.sigils.includes(id))return false;this.save.equippedSigil=id;if(intensity!==null)this.save.sigilIntensity=Math.max(1,Math.min(this.save.sigilMaxIntensity||1,Number(intensity)||1));this.sound?.play('note');this.persist('sigil-equip');return true;}
  facingVector(){return this.player.facing==='left'?{x:-1,y:0}:this.player.facing==='right'?{x:1,y:0}:this.player.facing==='up'?{x:0,y:-1}:{x:0,y:1};}
  ngPlusEchoForRoom(room=this.room()){
    if(!this.save.ngPlus)return null;const e=NGPLUS_ECHOES[room.id];if(!e||(this.save.ngPlusEchoes||[]).includes(e.id))return null;
    const source=this.save.ngPlusSourceEnding,sourceLine=source==='normal'?'A trace of THE HOUSE OF WITNESSES remains: contradiction is allowed to survive.':source==='dark'?'A trace of THE NINTH TENANT remains: the memory is wary of anything too perfectly consistent.':source==='true'?'A trace of NO ONE REMEMBERS ALONE remains: what was released can return without becoming property.':'The previous ending leaves no stable label.';
    const all=(this.save.endingsSeen||[]).length===3?'Three incompatible endings are now remembered at once. Blackthorn cannot make them agree.':null;
    return {...e,kind:'ngplus-echo',text:[...e.text,sourceLine,...(all?[all]:[]),`Cycle ${this.save.ngPlusCycle} · Refracted Memory ${(this.save.ngPlusEchoes||[]).length+1}/${NGPLUS_ECHO_TARGET}`]};
  }
  collectNgPlusEcho(e){if(!e||!this.save.ngPlus)return false;if(!Array.isArray(this.save.ngPlusEchoes))this.save.ngPlusEchoes=[];if(this.save.ngPlusEchoes.includes(e.id))return false;this.save.ngPlusEchoes.push(e.id);this.addFlag(`ngplus:echo:${e.id}`);if(this.save.ngPlusEchoes.length>=NGPLUS_ECHO_TARGET){this.save.ngPlusEchoComplete=true;this.unlockAchievement('refracted-nine');}this.persist('ngplus-echo');this.sound?.play('whisper');this.message(e.text);return true;}
  interact(){
    if(this.mode!=='playing')return;const room=this.room(),ngEcho=this.ngPlusEchoForRoom(room),items=ngEcho?[...(room.interact||[]),ngEcho]:(room.interact||[]);let nearest=null,nd=32;for(const it of items){if(it.once&&this.save.flags.includes(`seen:${it.id}`))continue;const d=Math.hypot((it.x+it.w/2)-(this.player.x+5),(it.y+it.h/2)-(this.player.y+7));if(d<nd){nearest=it;nd=d;}}
    if(!nearest)return;this.collectLore(nearest.id);const seen=()=>{if(nearest.once)this.addFlag(`seen:${nearest.id}`);};
    if(nearest.kind==='ngplus-echo'){this.collectNgPlusEcho(nearest);return;}
    if(nearest.kind==='anchor'){
      seen();this.addFlag('anchor:saint-orren');this.unlockAchievement('first-anchor');this.message(nearest.text,()=>{this.save.health=100;this.save.perception=Math.max(62,this.save.perception);this.save.stability=100;this.loadRoom('echo-priory-gate',true);});return;
    }
    if(nearest.kind==='memory-anchor'){
      const req=nearest.requiresFlags||[];if(!hasAll(req,this.save.flags)){this.message(['THE SPINE IS COLD','Another recovered memory must connect to this one first.']);return;}
      seen();this.addFlag(nearest.flag||`anchor:${nearest.target}`);if(nearest.weapon)this.unlockWeapon(nearest.weapon,false);this.save.health=100;this.save.perception=Math.max(62,this.save.perception);this.save.stability=100;this.save.memorySafeRoom=nearest.target;this.persist('memory-anchor');this.message(nearest.text||['A recovered century opens.'],()=>this.loadRoom(nearest.target,true));return;
    }
    if(nearest.kind==='final-entry'){
      if(this.save.phase9Complete){this.resolveEnding();return;}
      if(!this.save.phase8Complete){this.message(['THE ROOT DOOR HAS EIGHT COLD DEPRESSIONS','Recover all eight historical Memory Spines before entering the room behind memory.']);return;}
      this.addFlag('final:entered');this.unlockAchievement('root-door-open');this.save.health=100;this.save.perception=Math.max(72,this.save.perception);this.save.stability=100;this.save.memorySafeRoom='final-pale-threshold';this.persist('final-entry');this.message(nearest.text||['The Root Door opens.'],()=>this.loadRoom('final-pale-threshold',true));return;
    }
    if(nearest.kind==='final-choice'){
      const group=nearest.choiceGroup||nearest.id,value=nearest.choiceValue||nearest.id;this.save.finalChoices=this.save.finalChoices||{};
      if(this.save.finalChoices[group]){this.message(['THE CHOICE IS ALREADY PART OF THE MEMORY',`Elena chose: ${String(this.save.finalChoices[group]).toUpperCase()}.`]);return;}
      this.save.finalChoices[group]=value;this.addFlag(`final:choice-${group}`);this.addFlag(`final:choice-${group}:${value}`);this.persist('final-choice');this.sound?.play('note');this.message(nearest.text||[nearest.label]);return;
    }
    if(nearest.kind==='final-sequence'){
      const req=nearest.requiresFlags||[];if(!hasAll(req,this.save.flags)){this.message(['THE RELATION HAS NO CONTEXT','Another part of the final reconstruction is still missing.']);return;}
      const expected=(this.save.finalSequenceStep||0)+1;if(Number(nearest.step)===expected){this.save.finalSequenceStep=expected;this.spawnText(`RELATION ${expected}/${nearest.total||3}`,nearest.x-7,nearest.y-5);this.sound?.play('boss');if(expected===(nearest.total||3)){this.addFlag(nearest.flag||'final:route-coherent');this.unlockAchievement('three-relations');this.message([...nearest.text,'The final route stops trying to become one story.']);}else this.message([...nearest.text,`The relation holds: ${expected}/${nearest.total||3}.`]);}else{this.save.finalSequenceStep=0;this.perceptionSystem.shockLoss(this.save,4);this.sound?.play('hurt');this.message(['THE RELATIONS COLLAPSE','The route must be rebuilt from its first relation.']);}this.persist('final-sequence');return;
    }
    if(nearest.kind==='final-sigil-puzzle'){
      const done=this.save.finalSigilFlags?.includes(nearest.id);this.message(done?[nearest.label.toUpperCase(),'The formula is holding.']:nearest.text);return;
    }
    if(nearest.kind==='final-perception-anchor'){
      this.save.perception=Math.min(this.save.perception,24);this.save.stability=Math.max(42,this.save.stability);this.addFlag('final:perception-accepted');this.persist('final-perception');this.sound?.play('glitch');this.message(nearest.text||['Elena looks directly into the absence.']);return;
    }
    if(nearest.kind==='final-boss-focus'&&room.boss){
      const boss=this.enemies.find(e=>e.boss&&!e.dead);if(!boss||boss.type!==(nearest.bossType||'the-unremembered'))return;
      const required=['final:boss-mind','final:boss-flesh','final:boss-void','final:perception-accepted','final:choice-witness','final:choice-name','final:choice-burden'];const missing=required.filter(x=>!this.save.flags.includes(x));
      if(missing.length){this.message(['THE ENTITY STILL HAS TOO MANY EXITS','Three Sigil relations, deliberate low Perception and all three carried choices must be present at once.']);return;}
      this.bossVulnerable=BALANCE.boss.finalWindow;this.addFlag('final:boss-local');this.sound?.play('boss');this.screenShake=.45;this.message(nearest.text||['The Unremembered becomes local enough to wound.']);return;
    }
    if(nearest.kind==='sigil'&&nearest.sigil&&!this.save.sigils.includes(nearest.sigil)){this.save.sigils.push(nearest.sigil);this.save.equippedSigil=nearest.sigil;this.persist('sigil-discovery');}
    if(nearest.kind==='bell'&&room.boss){this.bossVulnerable=BALANCE.boss.bellWindow;this.perceptionSystem.shockLoss(this.save,5);this.sound?.play('boss');this.screenShake=.35;this.message(['THE FRAME RINGS WITHOUT METAL','For a few seconds the thing has an outline.']);return;}
    if(nearest.kind==='safe'){
      this.save.safeRoom=room.id;this.player.hp=100;this.save.health=100;this.save.perception=Math.min(100,this.save.perception+28);this.save.stability=100;this.save.stamina=100;this.persist('safe-room');this.sound?.play('note');this.message(nearest.text||['A stable memory forms here.']);return;
    }
    if(nearest.kind==='map'){
      seen();this.save.mapUnlocked=true;this.addFlag(nearest.flag||'map:estate');this.unlockAchievement('cartographer');this.persist('manor-map');this.message(nearest.text);return;
    }
    if(['key','mark','shortcut'].includes(nearest.kind)){
      seen();this.addFlag(nearest.flag);if(nearest.kind==='shortcut'&&this.save.flags.includes('shortcut:garden-service')&&this.save.flags.includes('shortcut:service-vestibule'))this.unlockAchievement('two-ways-home');this.persist(nearest.kind);this.sound?.play('note');this.message(nearest.text||[nearest.label]);return;
    }
    if(nearest.kind==='chapter-item'){
      seen();this.addFlag(nearest.flag);this.persist('chapter-item');this.sound?.play('note');this.message(nearest.text||[nearest.label]);return;
    }
    if(nearest.kind==='chapter-safe'){
      this.save.memorySafeRoom=room.id;this.player.hp=100;this.save.health=100;this.save.perception=Math.min(100,this.save.perception+22);this.save.stability=100;this.save.stamina=100;this.persist('chapter-checkpoint');this.sound?.play('note');this.message(nearest.text||['The memory steadies here.']);return;
    }
    if(nearest.kind==='sound-lure'){
      seen();this.noisePulse=3;this.addFlag(nearest.flag||`sound:${nearest.id}`);this.save.chapter1Stats.soundStrikes++;if(nearest.spawnEnemy){const d=ENEMY_TYPES[nearest.spawnEnemy];if(d){const spawned=this.spawnEnemy({type:nearest.spawnEnemy,x:250,y:126},this.enemies.length);spawned.attackCd=.35;this.enemies.push(spawned);this.save.chapter1Stats.hollowsDrawn++;}}this.persist('sound-lure');this.sound?.play('boss');this.screenShake=.12;this.message(nearest.text||['The sound travels farther than it should.']);return;
    }
    if(nearest.kind==='sound-seal'){
      const expected=(this.save.chapter1PuzzleStep||0)+1;this.noisePulse=3;this.save.chapter1Stats.soundStrikes++;if(Number(nearest.step)===expected){this.save.chapter1PuzzleStep=expected;this.sound?.play('boss');this.spawnText(`RESONANCE ${expected}/3`,nearest.x-5,nearest.y-5);if(expected===3){this.addFlag('chapter:sound-route');this.unlockAchievement('three-resonators');this.message([...nearest.text,'Stone grinds behind the ossuary. The wall remembers a doorway.']);}else this.message([...nearest.text,`The sequence holds: ${expected}/3.`]);}else{this.save.chapter1PuzzleStep=0;this.sound?.play('hurt');this.perceptionSystem.shockLoss(this.save,4);this.message(['THE RESONANCE COLLAPSES','The tones return in the wrong order. Begin again at the first basin.']);}this.persist('sound-seal');return;
    }
    if(nearest.kind==='chapter-mixture'){
      if(nearest.flag&&this.save.flags.includes(nearest.flag)){this.message(['THE FUMIGATION STILL BURNS','The mixture is complete. The lower route is warded.']);return;}const req=nearest.requiresFlags||[];if(!hasAll(req,this.save.flags)){const missing=req.filter(x=>!this.save.flags.includes(x)).map(x=>x.split(':').pop().toUpperCase());this.message(['THE RECIPE IS INCOMPLETE',`Missing: ${missing.join(' · ')}`,'Search the apothecary, nave and cloister before descending.']);return;}this.addFlag(nearest.flag||'chapter:ward-mixture');this.persist('chapter-mixture');this.sound?.play('win');this.message(nearest.text||['The ward holds.']);return;
    }
    if(nearest.kind==='lore-secret'){if(nearest.flag&&this.save.flags.includes(nearest.flag)){this.message(nearest.text||[nearest.label]);return;}this.addFlag(nearest.flag||`secret:${nearest.id}`);this.persist('lore-secret');this.sound?.play('whisper');this.message(nearest.text||[nearest.label]);return;}
    if(nearest.kind==='chapter-secret'){
      if(nearest.flag&&this.save.flags.includes(nearest.flag)){this.message(nearest.text||[nearest.label]);return;}this.addFlag(nearest.flag||`secret:${nearest.id}`);this.save.chapter1Stats.secrets++;this.unlockAchievement('patient-nine');this.persist('chapter-secret');this.sound?.play('whisper');this.message(nearest.text||[nearest.label]);return;
    }
    if(nearest.kind==='memory-item'){
      if(nearest.flag&&this.save.flags.includes(nearest.flag)){this.message(nearest.text||[nearest.label]);return;}seen();this.addFlag(nearest.flag||`memory:${nearest.id}`);this.persist('memory-item');this.sound?.play('note');this.message(nearest.text||[nearest.label]);return;
    }
    if(nearest.kind==='memory-safe'){
      this.save.memorySafeRoom=room.id;this.player.hp=100;this.save.health=100;this.save.perception=Math.min(100,this.save.perception+24);this.save.stability=100;this.save.stamina=100;this.persist('memory-safe');this.sound?.play('note');this.message(nearest.text||['This memory steadies here.']);return;
    }
    if(nearest.kind==='memory-secret'){
      if(nearest.flag&&this.save.flags.includes(nearest.flag)){this.message(nearest.text||[nearest.label]);return;}this.addFlag(nearest.flag||`secret:${nearest.id}`);const ch=nearest.chapter||'c2';this.save.chapterStats=this.save.chapterStats||{};this.save.chapterStats[ch]=this.save.chapterStats[ch]||{secrets:0};this.save.chapterStats[ch].secrets++;if(nearest.achievement)this.unlockAchievement(nearest.achievement);this.persist('memory-secret');this.sound?.play('whisper');this.message(nearest.text||[nearest.label]);return;
    }
    if(nearest.kind==='memory-sequence'){
      const req=nearest.requiresFlags||[];if(!hasAll(req,this.save.flags)){this.message(['THE MECHANISM LACKS CONTEXT','A related object in this memory has not been recovered yet.']);return;}const ch=nearest.chapter||'c2';this.save.chapterProgress=this.save.chapterProgress||{c2:0,c3:0,c4:0};const expected=(this.save.chapterProgress[ch]||0)+1;if(Number(nearest.step)===expected){this.save.chapterProgress[ch]=expected;this.sound?.play('boss');this.spawnText(`${ch.toUpperCase()} ${expected}/${nearest.total||3}`,nearest.x-5,nearest.y-5);if(expected===(nearest.total||3)){this.addFlag(nearest.completeFlag);this.sound?.play('win');this.message([...nearest.text,'The route now agrees with itself.']);}else this.message([...nearest.text,`The sequence holds: ${expected}/${nearest.total||3}.`]);}else{this.save.chapterProgress[ch]=0;this.perceptionSystem.shockLoss(this.save,3);this.sound?.play('hurt');this.message(['THE PATTERN LOSES COHERENCE','The sequence must be rebuilt from its first step.']);}this.persist('memory-sequence');return;
    }
    if(nearest.kind==='boss-focus'&&room.boss){const boss=this.enemies.find(e=>e.boss&&!e.dead);if(!boss){this.message(['ONLY THE AFTERIMAGE REMAINS']);return;}if(nearest.bossType&&boss.type!==nearest.bossType)return;this.bossVulnerable=BALANCE.boss.focusWindow;this.perceptionSystem.shockLoss(this.save,4);this.sound?.play('boss');this.screenShake=.3;this.message(nearest.text||['The boss is forced into a stable outline.']);return;}
    if(nearest.kind==='combat-trial'){
      if(!this.save.phase3Complete){this.message(['THE WEAPON IMPRINT REMAINS FLAT','Calibrate Perception in the Mirror Room before asking Blackthorn to reconstruct combat memories.']);return;}
      for(const id of ['candlestick','woodsman-axe','ritual-dagger','service-revolver'])this.unlockWeapon(id,false);this.save.ammo=this.save.ammo||{};this.save.ammo.revolver={clip:6,reserve:18};this.save.weapon='candlestick';this.persist('combat-imprint');this.message(nearest.text,()=>this.loadRoom('combat-imprint-arena',true));return;
    }
    if(nearest.kind==='combat-return'){
      if(this.enemies.some(e=>!e.dead)){this.message(['THE IMPRINT IS STILL ACTIVE','Three hostile patterns must be resolved before the Vault can collapse this reconstruction.']);return;}
      this.loadRoom('manor-memory-vault',true);return;
    }
    if(nearest.kind==='sigil-trial'){
      if(!this.save.phase4Complete){this.message(['THE LATTICE WILL NOT OPEN','Calibrate combat first. The grammar expects Elena to understand timing before consequence.']);return;}
      const ids=['bind-void-i','sever-void-i','brand-void-i','shift-void-i','ward-mind-i','reveal-mind-i','lure-mind-i','echo-mind-i','mend-flesh-i','fortify-flesh-i','purge-flesh-i','siphon-flesh-i'];for(const id of ids)if(!this.save.sigils.includes(id))this.save.sigils.push(id);this.save.sigilMaxIntensity=3;this.save.sigilIntensity=Math.min(3,Math.max(1,this.save.sigilIntensity||1));this.save.sigilPuzzleFlags=[];this.persist('sigil-lattice-open');this.message(nearest.text,()=>this.loadRoom('sigil-lattice-arena',true));return;
    }
    if(nearest.kind==='sigil-puzzle'){
      const done=this.save.sigilPuzzleFlags?.includes(nearest.id);this.message(done?[nearest.label.toUpperCase(),'The formula is holding. The lattice no longer resists here.']:nearest.text);return;
    }
    if(nearest.kind==='sigil-return'){
      const required=['lattice-mind','lattice-flesh','lattice-void'];if(!required.every(x=>this.save.sigilPuzzleFlags?.includes(x))){this.message(['THE GRAMMAR IS INCOMPLETE','Three fixtures remain: MIND must reveal, FLESH must purge, VOID must bind.']);return;}this.completeSigilTrial();return;
    }
    if(nearest.kind==='perception-trial'){
      if(!this.save.phase2Complete){this.message(['THE MIRROR REFUSES DEPTH','The Memory Index below the house must be understood first.']);return;}
      const current=Math.max(0,Number(this.save.perceptionTrialStep)||0);
      if(current>=4){
        this.save.perception=100;this.save.stability=100;this.save.perceptionTrialStep=0;this.save.phase3Complete=true;this.addFlag('perception:calibrated');this.unlockAchievement('unreliable-witness');this.persist('phase3-complete');this.sound?.setPerception(0,0);this.sound?.play('win');this.message(['PERCEPTION CALIBRATION COMPLETE','Elena knows the difference between a memory changing and a system actually failing.','Blackthorn can lie about what she sees. It cannot touch the browser, files or real saves.'],()=>this.onComplete?.('phase3'));return;
      }
      const step=current+1,values=[70,45,20,8],stability=[76,58,34,16];this.save.perceptionTrialStep=step;this.save.perception=values[step-1];this.save.stability=stability[step-1];this.recordPerceptionTier(step);this.persist('perception-trial');this.sound?.play(step>=3?'glitch':'whisper');const msg=this.perceptionSystem.tierMessage(step)||['PERCEPTION'];this.message([...nearest.text,...msg,step<4?'Interact with the mirror again when you are ready to descend further.':'Interact once more to end the controlled descent and restore a stable reading.']);return;
    }
    if(nearest.kind==='perception'){
      seen();this.perceptionSystem.shockLoss(this.save,14);this.save.stability=Math.max(0,this.save.stability-8);this.screenShake=.2;this.persist('perception-event');this.sound?.play('hurt');this.message(nearest.text);return;
    }
    if(nearest.kind==='phase2-finale'){
      seen();this.save.phase2Complete=true;this.addFlag('hub:index-understood');this.unlockAchievement('house-indexed');this.persist('phase2-complete');this.sound?.play('win');this.message(nearest.text,()=>this.onComplete?.('phase2'));return;
    }
    seen();if(!this.save.notes.includes(nearest.id))this.save.notes.push(nearest.id);this.sound?.play('note');this.persist('note');this.message(nearest.text||[nearest.label]);
  }
  resolveSigilPuzzle(sigil,intensity){
    const room=this.room();let changed=false;if(room.sigilTrial){for(const it of room.interact||[]){if(it.kind!=='sigil-puzzle'||this.save.sigilPuzzleFlags.includes(it.id))continue;const d=Math.hypot((it.x+it.w/2)-(this.player.x+5),(it.y+it.h/2)-(this.player.y+7));if(d>54||it.requiredSigil!==sigil.id||intensity<(it.requiredIntensity||1))continue;this.save.sigilPuzzleFlags.push(it.id);this.addFlag(`sigil:${it.id}`);this.spawnText('FORMULA HOLDS',it.x-8,it.y-5);this.sound?.play('win');changed=true;}if(changed&&['lattice-mind','lattice-flesh','lattice-void'].every(x=>this.save.sigilPuzzleFlags.includes(x)))this.unlockAchievement('grammar-of-three');}
    this.save.finalSigilFlags=this.save.finalSigilFlags||[];for(const it of room.interact||[]){if(it.kind!=='final-sigil-puzzle'||this.save.finalSigilFlags.includes(it.id))continue;if(it.id.startsWith('final-boss-')&&this.bossPhase<3)continue;const d=Math.hypot((it.x+it.w/2)-(this.player.x+5),(it.y+it.h/2)-(this.player.y+7));if(d>58||it.requiredSigil!==sigil.id||intensity<(it.requiredIntensity||1))continue;this.save.finalSigilFlags.push(it.id);this.addFlag(`final:sigil:${it.id}`);if(it.id.startsWith('final-boss-'))this.addFlag(`final:boss-${it.id.split('-').at(-1)}`);this.spawnText('RELATION HOLDS',it.x-10,it.y-5);this.sound?.play('win');changed=true;}
    if(['final-lattice-mind','final-lattice-flesh','final-lattice-void'].every(x=>this.save.finalSigilFlags.includes(x))){this.addFlag('final:lattice-complete');this.unlockAchievement('three-schools-final');}
    if(['final-boss-mind','final-boss-flesh','final-boss-void'].every(x=>this.save.finalSigilFlags.includes(x)))this.addFlag('final:boss-lattice');
    if(changed)this.persist('final-sigil');return changed;
  }
  completeSigilTrial(){if(this.save.phase5Complete){this.loadRoom('manor-memory-vault',true);return;}this.save.phase5Complete=true;this.save.sigilMaxIntensity=3;this.addFlag('sigils:calibrated');this.unlockAchievement('twelve-words');this.persist('phase5-complete');this.sound?.play('win');this.message(['SIGIL LATTICE COMPLETE','The twelve formulas are not twelve spells. They are twelve ways to phrase pressure against memory.','FLESH changes the body and corruption. MIND changes attention and interpretation. VOID changes boundaries, continuity and distance.','Intensity I is economical. II is committed. III is powerful enough to solve structures — and expensive enough to matter.'],()=>{this.loadRoom('manor-memory-vault',true);this.onComplete?.('phase5');});}
  completeCombatTrial(){if(this.save.phase4Complete)return;this.save.phase4Complete=true;this.addFlag('combat:calibrated');this.unlockAchievement('four-ways-to-hurt');this.persist('phase4-complete');this.sound?.play('win');this.message(['WEAPON IMPRINT COMPLETE','Elena has not become a soldier. She has learned what the house remembers about timing: distance, commitment, recoil and the instant before impact.','Future memories can now use the same combat grammar without sharing the same weapons.'],()=>{this.save.weapon='candlestick';this.loadRoom('manor-memory-vault',true);this.onComplete?.('phase4');});}
  resolveEnding(){
    if(!this.save.phase9Complete){this.message(['THE ROOT DOOR IS NOT AN EXIT YET']);return null;}
    const result=evaluateEnding(this.save),id=result.id;
    this.save.phase12Complete=true;this.save.ending=id;if(!Array.isArray(this.save.endingsSeen))this.save.endingsSeen=[];if(!this.save.endingsSeen.includes(id))this.save.endingsSeen.push(id);
    this.save.endingStats={secretCount:result.secretCount,keyEvidence:result.keyEvidence,keyEvidenceTarget:result.keyEvidenceTarget,sigilMastery:result.sigilMastery,finalGrammar:result.finalGrammar,darkSignals:result.darkSignals,choicesTrue:result.choicesTrue,loreCount:(this.save.lore||[]).length};
    this.addFlag(`ending:${id}`);this.unlockAchievement(result.profile.achievement);if(id==='true')this.unlockAchievement('true-ending');
    this.persist(`ending-${id}`);this.sound?.play('win');this.mode='ending';this.onEnding?.(result);return result;
  }
  completeBoss(e){if(e.type==='bell-boss'){this.completeSlice();return;}if(e.type==='the-unremembered'){this.completeFinalChapter(e);return;}const map={'salt-astronomer':'c2','last-enumerator':'c3','anatomist-shadow':'c4','first-tenant':'c5','company-without-faces':'c6','dead-frequency':'c7','man-missing-frame':'c8'};const ch=map[e.type];if(ch){this.completeHistoricalChapter(ch,e);return;}this.persist('boss');}
  completeHistoricalChapter(ch,e){
    const cfg={c2:{flag:'chapter:salt-stars-complete',boss:'salt-astronomer',achievement:'salt-stars-complete',stage:3,title:'THE SALT ASTRONOMER · FIXED',lines:['Nara restores the seventh star to the sky by admitting it was never a star at all — it was a missing destination.','Asterion was built around a hole in collective memory. Blackthorn contains the same geometry in miniature.']},c3:{flag:'chapter:last-census-complete',boss:'last-enumerator',achievement:'last-census-complete',stage:4,title:'THE LAST ENUMERATOR · COUNTED',lines:['Marcus stops correcting the census and instead preserves the contradictions.','The Unremembered thrives when records are forced to agree. Disagreement can be evidence.']},c4:{flag:'chapter:anatomy-shadow-complete',boss:'anatomist-shadow',achievement:'anatomy-shadow-complete',stage:5,title:"THE ANATOMIST'S SHADOW · SEVERED",lines:['Lucia proves the second body is made from remembered relationships, not flesh.','When the mirrors collapse, her shadow returns half a heartbeat late — but it returns.']},c5:{flag:'chapter:house-name-complete',boss:'first-tenant',achievement:'house-name-complete',stage:6,title:'THE FIRST TENANT · EVICTED',lines:['Eleanor gives the impossible room a defined relationship to the house.','Blackthorn becomes an intentional mnemonic engine.']},c6:{flag:'chapter:mud-remembers-complete',boss:'company-without-faces',achievement:'mud-remembers-complete',stage:7,title:'THE COMPANY WITHOUT FACES · NAMED',lines:['Elias preserves contradictory witness accounts instead of collapsing them.','Two imperfect memories can resist one perfect erasure.']},c7:{flag:'chapter:broadcast-eleven-complete',boss:'dead-frequency',achievement:'broadcast-eleven-complete',stage:8,title:'THE DEAD FREQUENCY · LOCKED',lines:['Naomi proves the eleventh signal is a carrier for remembered relationships.','Blackthorn is a pattern before it is a place.']},c8:{flag:'chapter:tape-zero-complete',boss:'man-missing-frame',achievement:'tape-zero-complete',stage:8,title:'THE MAN IN THE MISSING FRAME · HELD',lines:['Theo preserves the impossible frame rather than editing it away.','His final tape is addressed to Elena.']}}[ch];if(!cfg)return;if(!this.save.bosses.includes(cfg.boss))this.save.bosses.push(cfg.boss);this.addFlag(cfg.flag);this.unlockAchievement(cfg.achievement);this.save.houseStage=Math.max(cfg.stage,this.save.houseStage||0);this.save.memorySafeRoom='echo-priory-gate';if(ch==='c4'){this.save.phase7Complete=true;this.unlockAchievement('phase7-complete');}if(ch==='c8'){this.save.phase8Complete=true;this.unlockAchievement('phase8-complete');}this.persist(`chapter-${ch}-complete`);this.message([cfg.title,...cfg.lines,'The memory tears back toward Blackthorn Manor.'],()=>{this.save.weapon='candlestick';this.save.health=100;this.save.perception=Math.max(58,this.save.perception);this.save.stability=100;this.loadRoom('manor-memory-vault',true);if(ch==='c4')this.onComplete?.('phase7');if(ch==='c8')this.onComplete?.('phase8');});}
  completeFinalChapter(e){
    if(!this.save.bosses.includes('the-unremembered'))this.save.bosses.push('the-unremembered');this.save.phase9Complete=true;this.save.houseStage=Math.max(9,this.save.houseStage||0);this.addFlag('chapter:final-complete');this.unlockAchievement('unremembered-defeated');this.unlockAchievement('phase9-complete');this.persist('phase9-complete');
    const choices=this.save.finalChoices||{},w=choices.witness||'unmade',n=choices.name||'unmade',b=choices.burden||'unmade';
    this.message(['THE UNREMEMBERED · MADE LOCAL','It does not die like a body. It loses the ability to be everywhere a relationship has been erased.','Elena reaches Blackthorn again carrying three unresolved choices.',`Witness: ${w.toUpperCase()} · Name: ${n.toUpperCase()} · Burden: ${b.toUpperCase()}`,'The house has not chosen an ending for her. Not yet.'],()=>{this.save.weapon='candlestick';this.save.health=100;this.save.perception=72;this.save.stability=100;this.save.safeRoom='manor-library';this.loadRoom('manor-root-door',true);this.onComplete?.('phase9');});
  }
  completeSlice(){
    if(!this.save.bosses.includes('bell-without-tongue'))this.save.bosses.push('bell-without-tongue');this.save.sliceComplete=true;this.save.phase6Complete=true;this.save.houseStage=Math.max(2,this.save.houseStage||0);this.save.memorySafeRoom='echo-priory-gate';this.addFlag('chapter:saint-orren-complete');this.unlockAchievement('bell-silenced');this.unlockAchievement('saint-orren-complete');this.persist('boss');
    this.message(['THE BELL WITHOUT A TONGUE · SILENCED','Ysabel finally remembers all twenty-one names. Nine of them were never buried because the priory forgot they had existed.','She removed the clapper not to silence the bell — but to deny the Unremembered a tongue made from human recollection.','The memory tears open. Blackthorn has learned the whole shape of Saint Orren.'],()=>{this.save.weapon='candlestick';this.save.health=100;this.save.perception=Math.max(55,this.save.perception);this.save.stability=100;this.save.room='manor-gallery-after';this.loadRoom('manor-gallery-after',true);this.onComplete?.('phase6');});
  }
  update(dt){
    this.roomTime+=dt;this.noisePulse=Math.max(0,(this.noisePulse||0)-dt);this.staminaRegenDelay=Math.max(0,(this.staminaRegenDelay||0)-dt);if(this.hitStop>0){this.hitStop=Math.max(0,this.hitStop-dt);this.updateParticles(dt);this.hud();return;}this.attackCd=Math.max(0,this.attackCd-dt);this.heavyCd=Math.max(0,this.heavyCd-dt);this.parryTimer=Math.max(0,this.parryTimer-dt);this.invuln=Math.max(0,this.invuln-dt);this.dodgeTimer=Math.max(0,this.dodgeTimer-dt);this.sigilCooldown=Math.max(0,this.sigilCooldown-dt);this.sigilFlash=Math.max(0,this.sigilFlash-dt);for(const k of Object.keys(this.sigilBuffs))this.sigilBuffs[k]=Math.max(0,(this.sigilBuffs[k]||0)-dt);this.bossVulnerable=Math.max(0,this.bossVulnerable-dt);this.screenShake=Math.max(0,this.screenShake-dt);this.comboTimer=Math.max(0,this.comboTimer-dt);if(this.comboTimer<=0)this.combo=0;if(this.charging)this.chargeTime=Math.min(this.weapon.chargeMax||1.2,this.chargeTime+dt);if(this.reloadTimer>0){this.reloadTimer=Math.max(0,this.reloadTimer-dt);if(this.reloadTimer<=0)this.finishReload();}
    this.player.hitFlash=Math.max(0,this.player.hitFlash-dt);for(const e of this.enemies){e.hitFlash=Math.max(0,e.hitFlash-dt);e.bound=Math.max(0,e.bound-dt);e.attackCd=Math.max(0,e.attackCd-dt);e.stagger=Math.max(0,(e.stagger||0)-dt);e.confused=Math.max(0,(e.confused||0)-dt);e.branded=Math.max(0,(e.branded||0)-dt);if(e.branded<=0)e.brandPower=1;if(e.poise<e.maxPoise&&e.stagger<=0)e.poise=Math.min(e.maxPoise,e.poise+e.maxPoise*.12*dt);}
    this.save.playSeconds=(this.save.playSeconds||0)+dt;const regen=this.guard?BALANCE.stamina.guardRegen:this.charging?BALANCE.stamina.chargeRegen:BALANCE.stamina.idleRegen;if(this.staminaRegenDelay<=0)this.save.stamina=Math.min(100,this.save.stamina+regen*dt);
    this.updateMovement(dt);this.updateEnemies(dt);this.updateProjectiles(dt);this.updatePerception(dt);this.updateParticles(dt);this.checkExits();this.hud();
  }
  updateMovement(dt){
    let x=0,y=0;if(this.keys.has('ArrowLeft')||this.keys.has('KeyA')||this.touch.has('left'))x--;if(this.keys.has('ArrowRight')||this.keys.has('KeyD')||this.touch.has('right'))x++;if(this.keys.has('ArrowUp')||this.keys.has('KeyW')||this.touch.has('up'))y--;if(this.keys.has('ArrowDown')||this.keys.has('KeyS')||this.touch.has('down'))y++;
    if(!x&&!y)return;const l=Math.hypot(x,y)||1;x/=l;y/=l;if(Math.abs(x)>Math.abs(y))this.player.facing=x<0?'left':'right';else this.player.facing=y<0?'up':'down';const mult=this.guard?.5:this.charging?.58:1;this.tryMove(x*this.player.speed*mult*dt,y*this.player.speed*mult*dt);
  }
  tryMove(dx,dy){const room=this.room(),obs=room.obstacles||[];let nx={...this.player,x:this.player.x+dx};if(!obs.some(o=>overlaps(nx,{x:o[0],y:o[1],w:o[2],h:o[3]})))this.player.x=clamp(nx.x,1,INTERNAL_W-this.player.w-1);let ny={...this.player,y:this.player.y+dy};if(!obs.some(o=>overlaps(ny,{x:o[0],y:o[1],w:o[2],h:o[3]})))this.player.y=clamp(ny.y,1,INTERNAL_H-this.player.h-1);}
  pushFromExit(dir){if(dir==='right')this.player.x=286;else if(dir==='left')this.player.x=24;else if(dir==='up')this.player.y=24;else this.player.y=146;}
  blockedExit(room,dir){
    const rule=room.exitRules?.[dir];if(!rule)return null;
    if(rule.requiresSlice&&!this.save.sliceComplete)return rule.message||['THE HOUSE REFUSES THIS ROUTE'];
    if(rule.requiresFlags&&!hasAll(rule.requiresFlags,this.save.flags))return rule.message||['THE WAY IS LOCKED'];
    if(rule.requiresPhase2Future)return rule.message||['THIS ROUTE BELONGS TO A LATER MEMORY'];
    return null;
  }
  checkExits(){
    const room=this.room();let dir=null;if(this.player.x<18)dir='left';else if(this.player.x+this.player.w>302)dir='right';else if(this.player.y<18)dir='up';else if(this.player.y+this.player.h>162)dir='down';if(!dir||!room.exits?.[dir])return;
    if(room.lockedExit===dir&&room.clearUnlock&&this.enemies.some(e=>!e.dead)){this.pushFromExit(dir);this.message(['THE THRESHOLD WILL NOT OPEN','Something in the crypt still remembers you.']);return;}
    const blocked=this.blockedExit(room,dir);if(blocked){this.pushFromExit(dir);this.message(blocked);return;}
    const next=this.resolveRoomId(room.exits[dir]);this.save.health=this.player.hp;this.loadRoom(next,false);if(dir==='right')this.player.x=24;if(dir==='left')this.player.x=INTERNAL_W-36;if(dir==='down')this.player.y=24;if(dir==='up')this.player.y=INTERNAL_H-38;
  }
  updateEnemies(dt){
    const room=this.room();for(const e of this.enemies){if(e.dead)continue;if(e.boss){this.updateBoss(e,dt);continue;}if(e.bound>0||e.stagger>0)continue;const d=this.distanceToPlayer(e);if(e.confused>0){e.pendingAttack=false;const a=this.roomTime*2.1+e.x*.03;e.x=clamp(e.x+Math.cos(a)*e.speed*.35*dt,18,INTERNAL_W-e.w-18);e.y=clamp(e.y+Math.sin(a)*e.speed*.35*dt,18,INTERNAL_H-e.h-18);continue;}
      if(e.pendingAttack){e.windup=Math.max(0,e.windup-dt);if(e.windup<=0){e.pendingAttack=false;if(this.distanceToPlayer(e)<19)this.hitPlayer(e.damage,e);}continue;}
      let vx=0,vy=0;if(e.behavior==='edge'&&d>45){const center={x:160,y:90};vx=e.x<center.x?-1:1;vy=e.y<center.y?-1:1;}else if(e.behavior==='listener'){if(d<105&&(this.noisePulse>0||this.attackCd>.05||this.heavyCd>.1||Math.abs(this.player.x-e.x)<38)){vx=this.player.x-e.x;vy=this.player.y-e.y;}}else if(e.behavior==='sound'){if(d<118&&(this.noisePulse>0||this.attackCd>.05||this.heavyCd>.1)){vx=this.player.x-e.x;vy=this.player.y-e.y;}}else if(e.behavior==='ambush'){if(d<64||this.attackCd>.04||this.heavyCd>.08){vx=this.player.x-e.x;vy=this.player.y-e.y;}else{vx=Math.sin(this.roomTime+e.x)*.35;vy=Math.cos(this.roomTime*.8+e.y)*.35;}}else if(e.behavior==='orbit'){if(d<125){const tx=this.player.x-e.x,ty=this.player.y-e.y;vx=tx*.42-ty*.75;vy=ty*.42+tx*.75;}}else if(e.behavior==='flee'){if(d<70){vx=e.x-this.player.x;vy=e.y-this.player.y;}else if(d<130){vx=this.player.x-e.x;vy=this.player.y-e.y;}}else if(e.behavior==='blink'){if(d<115){vx=this.player.x-e.x;vy=this.player.y-e.y;if(Math.floor(this.roomTime*2.2+e.x)%7===0&&d>45){e.x=clamp(this.player.x+(seeded(this.roomTime+e.x)>.5?52:-52),18,INTERNAL_W-e.w-18);e.y=clamp(this.player.y+(seeded(this.roomTime+e.y)-.5)*60,18,INTERNAL_H-e.h-18);}}}else if(d<112){vx=this.player.x-e.x;vy=this.player.y-e.y;}
      const l=Math.hypot(vx,vy)||1;vx/=l;vy/=l;const oldx=e.x,oldy=e.y;e.x+=vx*e.speed*dt;e.y+=vy*e.speed*dt;if((room.obstacles||[]).some(o=>overlaps(e,{x:o[0],y:o[1],w:o[2],h:o[3]}))){e.x=oldx;e.y=oldy;}if(d<16&&e.attackCd<=0){e.pendingAttack=true;e.windup=e.windupMax;e.attackCd=1.0+e.windupMax;this.sound?.play('telegraph');}
    }
  }
  bossCanBeHit(e){return !e?.boss||this.bossPhase<3||this.bossVulnerable>0;}
  bossProfile(e){return BOSS_PROFILES[e.type]||BOSS_PROFILES['bell-boss'];}
  bossMove(e,profile,phase,dt){
    const px=this.player.x+this.player.w/2,py=this.player.y+this.player.h/2,ex=e.x+e.w/2,ey=e.y+e.h/2;let dx=px-ex,dy=py-ey,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d;const preferred=profile.preferred||70,s=e.speed*(phase===3?1.14:phase===2?1.04:.96);
    e.bossClock=(e.bossClock||0)+dt;e.teleportCd=Math.max(0,(e.teleportCd||0)-dt);
    if(profile.movement==='anchor'){e.x+=Math.cos(e.bossClock*1.35)*7*dt;e.y+=Math.sin(e.bossClock*.93)*5*dt;}
    else if(profile.movement==='orbit'){const radial=(d-preferred)/Math.max(30,preferred);e.x+=(nx*radial-ny*.72)*s*dt;e.y+=(ny*radial+nx*.72)*s*dt;}
    else if(profile.movement==='ledger'){const axis=Math.floor(e.bossClock/1.3)%2;e.x+=(axis?nx:Math.sign(dx))*.55*s*dt;e.y+=(axis?Math.sign(dy):ny)*.55*s*dt;}
    else if(profile.movement==='mirror'){e.x+=(-ny*.75+nx*(d>preferred?.32:-.28))*s*dt;e.y+=(nx*.75+ny*(d>preferred?.32:-.28))*s*dt;if(e.teleportCd<=0&&phase>=2){e.teleportCd=phase===3?1.7:2.4;e.x=clamp(px-(dx>0?54:-54),24,INTERNAL_W-e.w-24);e.y=clamp(py+(seeded(e.bossClock)-.5)*72,40,INTERNAL_H-e.h-24);this.spawnText('MIRROR STEP',e.x-10,e.y-6);}}
    else if(profile.movement==='threshold'){const horizontal=Math.floor(e.bossClock/1.1)%2===0;e.x+=(horizontal?nx*.95:nx*.22)*s*dt;e.y+=(horizontal?ny*.22:ny*.95)*s*dt;}
    else if(profile.movement==='formation'){const radial=d>preferred?1:d<preferred-18?-1:.05;e.x+=(nx*radial-ny*.35)*s*.72*dt;e.y+=(ny*radial+nx*.35)*s*.72*dt;}
    else if(profile.movement==='signal'){e.x+=Math.sin(e.bossClock*2.2)*s*.72*dt;e.y+=(py-ey)*.18*dt;}
    else if(profile.movement==='stutter'){if(e.teleportCd<=0){e.teleportCd=phase===3?1.2:phase===2?1.65:2.2;e.lastPlayerX=this.player.x;e.lastPlayerY=this.player.y;e.x=clamp(px+(seeded(e.bossClock*3)>.5?66:-66),24,INTERNAL_W-e.w-24);e.y=clamp(py+(seeded(e.bossClock*7)-.5)*82,40,INTERNAL_H-e.h-24);this.spawnText('FRAME LOST',e.x-7,e.y-6);}else{e.x+=nx*s*.28*dt;e.y+=ny*s*.28*dt;}}
    else {const radial=d>preferred?1:d<preferred-22?-.7:.05;e.x+=(nx*radial-ny*.48)*s*.82*dt;e.y+=(ny*radial+nx*.48)*s*.82*dt;}
    e.x=clamp(e.x,25,INTERNAL_W-e.w-25);e.y=clamp(e.y,42,INTERNAL_H-e.h-22);
  }
  hostileShot(x,y,angle,speed,damage,kind='boss',delay=0,life=3.4){this.projectiles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:2,life,damage,hostile:true,kind,delay});}
  aimedBossShot(e,speed,damage,kind='aimed',offset=0,delay=0){const x=e.x+e.w/2,y=e.y+e.h/2,a=Math.atan2((this.player.y+7)-y,(this.player.x+5)-x)+offset;this.hostileShot(x,y,a,speed,damage,kind,delay);}
  fireBossPattern(e,profile,phase){
    const cfg=profile.phases[phase-1],x=e.x+e.w/2,y=e.y+e.h/2,n=cfg.shots||6,k=profile.pattern,idx=e.patternIndex++||0;
    if(k==='bell-ring'){const rot=(idx%2)*Math.PI/n;for(let i=0;i<n;i++)this.hostileShot(x,y,rot+i*Math.PI*2/n,cfg.speed,cfg.damage,'bell-ring');}
    else if(k==='salt-star'){const rot=this.roomTime*.24;for(let i=0;i<7;i++)this.hostileShot(x,y,rot+i*Math.PI*2/7,cfg.speed,cfg.damage,'salt-star');if(phase>=2)this.aimedBossShot(e,cfg.speed*1.15,cfg.damage+1,'salt-comet',0,.18);}
    else if(k==='census-cross'){const rot=idx%2?Math.PI/4:0;for(let i=0;i<4;i++)this.hostileShot(x,y,rot+i*Math.PI/2,cfg.speed,cfg.damage,'census-axis');for(let i=0;i<Math.max(0,phase-1)*2;i++)this.aimedBossShot(e,cfg.speed,cfg.damage,'census-entry',(i-(phase-1)+.5)*.16,.12*i);}
    else if(k==='mirror-fan'){for(let i=0;i<n;i++){const spread=(i-(n-1)/2)*.13;this.aimedBossShot(e,cfg.speed,cfg.damage,'mirror-left',spread);this.aimedBossShot(e,cfg.speed,cfg.damage,'mirror-right',Math.PI-spread,.12);}}
    else if(k==='tenant-doors'){const rot=idx%2?Math.PI/4:0;for(let i=0;i<Math.max(4,n);i++)this.hostileShot(x,y,rot+i*Math.PI*2/Math.max(4,n),cfg.speed,cfg.damage,'tenant-threshold',i%2?.12:0);}
    else if(k==='company-volley'){const base=Math.atan2((this.player.y+7)-y,(this.player.x+5)-x);for(let row=0;row<Math.min(3,phase+1);row++)for(let i=0;i<n;i++){const spread=(i-(n-1)/2)*.11;this.hostileShot(x,y,base+spread,cfg.speed+row*4,cfg.damage,'company-volley',row*.22);}}
    else if(k==='frequency-band'){const ys=[50,82,114,146];for(let i=0;i<Math.min(ys.length,phase+1);i++){const yy=ys[(i+idx)%ys.length];this.projectiles.push({x:18,y:yy,vx:cfg.speed,vy:0,r:2,life:5,damage:cfg.damage,hostile:true,kind:'frequency-band',delay:i*.14});this.projectiles.push({x:302,y:yy+8,vx:-cfg.speed,vy:0,r:2,life:5,damage:cfg.damage,hostile:true,kind:'frequency-band',delay:i*.14+.08});}}
    else if(k==='missing-frame'){const tx=(e.lastPlayerX||this.player.x)+5,ty=(e.lastPlayerY||this.player.y)+7;for(let i=0;i<n;i++){const a=Math.atan2(ty-y,tx-x)+(i-(n-1)/2)*.12;this.hostileShot(x,y,a,cfg.speed,cfg.damage,'missing-frame',i*.08);}if(phase===3)this.aimedBossShot(e,cfg.speed*1.2,cfg.damage+1,'missing-cut',Math.PI,.35);}
    else {const rot=this.roomTime*.37;for(let i=0;i<n;i++)this.hostileShot(x,y,rot+i*Math.PI*2/n,cfg.speed,cfg.damage,'unremembered-ring',i%3*.08);for(let i=0;i<phase;i++)this.aimedBossShot(e,cfg.speed*1.1,cfg.damage,'relation-cut',(i-(phase-1)/2)*.18,.16*i);}
    this.perceptionSystem.shockLoss(this.save,cfg.perception||2);this.sound?.play('boss');
  }
  updateBoss(e,dt){
    const profile=this.bossProfile(e),phase=phaseForBoss(e.hp,e.maxHp),cfg=profile.phases[phase-1];
    if(phase!==this.bossPhase){this.bossPhase=phase;this.bossVulnerable=phase===3?0:Math.max(this.bossVulnerable,.35);this.screenShake=.3;this.sound?.play('boss');if(e.type==='the-unremembered'&&phase===3){this.save.perception=Math.min(this.save.perception,28);this.save.stability=Math.max(46,this.save.stability);this.finalBossPhase3=true;}this.message([`${e.name.toUpperCase()} · PHASE ${phase}`,cfg.line]);return;}
    this.bossAttackTimer-=dt;this.bossMove(e,profile,phase,dt);const d=this.distanceToPlayer(e);
    if(e.pendingAttack){e.windup=Math.max(0,e.windup-dt);if(e.windup<=0){e.pendingAttack=false;if(this.distanceToPlayer(e)<25)this.hitPlayer((e.damage+(phase-1)*2)*(cfg.melee||1),e);}}
    else if(d<23&&e.attackCd<=0){e.pendingAttack=true;e.windup=e.windupMax*(phase===3?.82:1);e.attackCd=.86+e.windupMax;this.sound?.play('telegraph');}
    if(this.bossAttackTimer<=0){this.bossAttackTimer=cfg.interval;this.fireBossPattern(e,profile,phase);}
  }
  hitPlayer(amount,source){
    if(this.invuln>0)return;if(this.sigilBuffs.fortify>0)amount*=.62;if(this.guard){if(this.parryTimer>0){if(source){source.bound=Math.max(source.bound||0,1.1);source.stagger=Math.max(source.stagger||0,.85);if(Number.isFinite(source.hp)&&source.hp<900)source.hp=Math.max(0,source.hp-2);}this.save.combatStats.parries++;this.unlockAchievement('perfect-answer');this.sound?.play('parry');this.spawnText('PARRY',this.player.x,this.player.y-4);this.hitStop=Math.max(this.hitStop,.07);return;}amount*=.35;this.save.stamina=Math.max(0,this.save.stamina-BALANCE.stamina.blockCost);this.staminaRegenDelay=Math.max(this.staminaRegenDelay,BALANCE.stamina.blockDelay);if(this.save.stamina<=0){this.guard=false;this.parryTimer=0;amount*=1.7;this.spawnText('GUARD BREAK',this.player.x-11,this.player.y-4);}}
    this.player.hp=Math.max(0,this.player.hp-amount);this.invuln=.55;this.screenShake=.18;this.perceptionSystem.shockLoss(this.save,amount*.45);this.sound?.play('hurt');if(this.player.hp<=0)this.playerDeath();
  }
  playerDeath(){this.save.deaths=(this.save.deaths||0)+1;this.save.health=100;this.save.perception=Math.max(45,this.save.perception);this.save.stability=75;const echo=this.room().tone!=='manor';const checkpoint=echo?(this.save.memorySafeRoom||'echo-priory-gate'):(this.save.safeRoom||'manor-vestibule');this.message(['MEMORY FRACTURE','The scene refuses to end here.','Blackthorn pulls the thread back to the last stable threshold.'],()=>this.loadRoom(checkpoint,true));}
  updateProjectiles(dt){for(const p of this.projectiles){if((p.delay||0)>0){p.delay=Math.max(0,p.delay-dt);p.life-=dt;if(p.life<=0)continue;continue;}p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)continue;if(p.hostile&&this.invuln<=0&&Math.hypot((this.player.x+5)-p.x,(this.player.y+7)-p.y)<8){p.life=0;this.hitPlayer(p.damage,{bound:0,hp:999});continue;}if(!p.hostile){for(const e of this.enemies){if(e.dead||Math.hypot((e.x+e.w/2)-p.x,(e.y+e.h/2)-p.y)>Math.max(7,e.w*.7))continue;if(e.boss&&!this.bossCanBeHit(e)){p.life=0;this.spawnText('UNFIXED',e.x,e.y);break;}p.life=0;const scaled=p.damage*(e.branded>0?(e.brandPower||1):1),dead=damageActor(e,scaled,{x:Math.sign(p.vx)*4,y:Math.sign(p.vy)*4});if(e.branded>0)e.branded=Math.max(0,e.branded-(p.heavy?2.5:1.4));this.applyPoise(e,p.poise||8);this.save.combatStats.rangedHits++;if(p.heavy)this.save.combatStats.heavyHits++;this.hitStop=Math.max(this.hitStop,p.heavy ? .045 : .024);this.spawnBurst(e.x+e.w/2,e.y+e.h/2,p.heavy?12:7);this.sound?.play('hit');if(dead)this.killEnemy(e);break;}}}this.projectiles=this.projectiles.filter(p=>p.life>0&&p.x>-5&&p.x<325&&p.y>-5&&p.y<185);}
  updatePerception(dt){
    const room=this.room();let corrupt=false;if(room.corruption){for(const z of room.corruption)if(overlaps(this.player,{x:z[0],y:z[1],w:z[2],h:z[3]})){corrupt=true;break;}}
    let pressure=0;for(const e of this.enemies)if(!e.dead&&this.distanceToPlayer(e)<85)pressure+=e.perception*BALANCE.perception.enemyPressureScale;
    if(this.sigilBuffs.purge>0){corrupt=false;pressure*=.55;}if(this.sigilBuffs.ward>0)pressure*=.72;this.perceptionSystem.update(dt,this.save,{corrupt,enemyPressure:pressure,safe:!!room.safe&&!corrupt});
    const fx=this.perceptionSystem.fx(this.save.perception,this.settings),tier=fx.tier;this.sound?.setPerception(tier,fx.amount);
    if(this.recordPerceptionTier(tier)){this.persist('perception-tier');const lines=this.perceptionSystem.tierMessage(tier);if(lines)this.message(lines);}
    if(this.sigilBuffs.reveal<=0&&this.perceptionSystem.shouldSpawnShadow(fx)&&this.phantoms.filter(p=>p.type==='shadow').length<3){this.phantoms.push({type:'shadow',x:18+seeded(this.roomTime*11)*276,y:34+seeded(this.roomTime*17+2)*112,w:9,h:20,life:1.45});}
    if(this.sigilBuffs.reveal<=0&&this.perceptionSystem.shouldSpawnPhantom(fx)&&this.phantoms.filter(p=>p.type==='enemy').length<3){let x=24+seeded(this.roomTime*13+5)*264,y=38+seeded(this.roomTime*19+9)*105;if(Math.hypot(x-this.player.x,y-this.player.y)<55)x=INTERNAL_W-x-16;this.phantoms.push({type:'enemy',x,y,w:11,h:17,life:fx.tier>=3?4.6:3.4});}
    if(this.perceptionSystem.shouldEcho(fx)){this.echoes.push({text:this.perceptionSystem.echoText(this.roomTime*7+room.name.length),life:2.6});this.sound?.play('whisper');}
    if(this.sigilBuffs.reveal<=0&&this.perceptionSystem.shouldGlitch(fx)){this.fakeGlitches.push({y:20+Math.floor(seeded(this.roomTime*23)*135),h:2+Math.floor(seeded(this.roomTime*31)*7),dx:2+Math.floor(seeded(this.roomTime*41)*9),life:.22});this.sound?.play('glitch');}
  }
  updateParticles(dt){for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}this.particles=this.particles.filter(p=>p.life>0);for(const p of this.phantoms)p.life-=dt;this.phantoms=this.phantoms.filter(p=>p.life>0);for(const e of this.echoes)e.life-=dt;this.echoes=this.echoes.filter(e=>e.life>0);for(const g of this.fakeGlitches)g.life-=dt;this.fakeGlitches=this.fakeGlitches.filter(g=>g.life>0);}
  spawnBurst(x,y,n=8){for(let i=0;i<n;i++){const a=seeded(this.roomTime+i)*Math.PI*2,s=12+seeded(i+this.roomTime)*24;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+seeded(i)*.35});}}
  spawnText(text,x,y){this.particles.push({x,y,vx:0,vy:-8,life:.65,text});}

  render(){
    const c=this.ctx,room=this.room(),fx=this.perceptionSystem.fx(this.save.perception,this.settings);c.save();let sx=0,sy=0;if(this.screenShake>0&&!this.settings.reduceMotion&&!this.settings.disableShake){sx=(Math.random()-.5)*3;sy=(Math.random()-.5)*3;}c.translate(sx,sy);
    this.drawRoom(c,room,fx);this.drawInteractables(c,room,fx);for(const p of this.phantoms)this.drawPhantom(c,p,fx);for(const e of this.enemies)if(!e.dead)this.drawEnemy(c,e,fx);this.drawPlayer(c);if(this.sigilFlash>0){c.save();c.globalAlpha=Math.min(.7,this.sigilFlash);const school=sigilById(this.save.equippedSigil).school;c.strokeStyle=school==='FLESH'?'#b1766b':school==='MIND'?'#8d89b0':'#9f78a6';const r=14+(1-this.sigilFlash)*28;c.strokeRect(this.player.x-r/2+5,this.player.y-r/2+7,r,r);c.restore();}for(const p of this.projectiles)this.drawProjectile(c,p);this.drawParticles(c);this.drawPerceptionEcho(c,fx);this.drawVignette(c,room,fx);this.drawFakeGlitches(c,fx);if(this.mode==='map')this.drawMap(c);c.restore();
  }
  palette(room){if(room.id?.startsWith('final-'))return {floor:'#16101d',wall:'#352442',trim:'#8c5d96',light:'#d49368',dark:'#030205',accent:'#b25e82'};if(room.tone==='boss')return {floor:'#160d0e',wall:'#382126',trim:'#8d594f',light:'#e0a15f',dark:'#030203',accent:'#b13d39'};if(room.tone==='manor')return {floor:'#151318',wall:'#352e31',trim:'#8f745b',light:'#e2a35f',dark:'#040405',accent:'#9e5b45'};if(['1198 BCE','395'].includes(room.era))return {floor:'#171411',wall:'#393126',trim:'#8f7958',light:'#e2ae6b',dark:'#050403',accent:'#9f6a3f'};if(['1917','1956','1987'].includes(room.era))return {floor:'#101519',wall:'#26323a',trim:'#647c82',light:'#d28c58',dark:'#030507',accent:'#7e4a3e'};return {floor:'#131416',wall:'#333332',trim:'#82745f',light:'#d9a05f',dark:'#040405',accent:'#75505c'};}
  drawRoom(c,room,fx){const p=this.palette(room);this.drawSceneBackdrop(c,room);c.save();c.globalAlpha=.82;c.fillStyle=p.floor;c.fillRect(16,78,288,86);c.restore();for(let y=82;y<164;y+=10)for(let x=20;x<304;x+=16){const j=seeded(x*7+y*13+room.name.length);c.fillStyle=j>.72?'rgba(103,91,78,.12)':j<.18?'rgba(0,0,0,.18)':'rgba(58,51,49,.10)';c.fillRect(x+(y%20?2:0),y,13,8);}for(const o of room.obstacles||[]){c.fillStyle='rgba(5,4,6,.82)';c.fillRect(o[0]+2,o[1]+4,o[2],o[3]);c.fillStyle=p.wall;c.fillRect(...o);c.fillStyle=p.trim;c.fillRect(o[0],o[1],o[2],Math.min(3,o[3]));c.fillStyle='#0a0809';c.fillRect(o[0],o[1]+o[3]-3,o[2],3);c.fillStyle='rgba(255,214,160,.09)';c.fillRect(o[0]+2,o[1]+3,1,Math.max(0,o[3]-7));}this.drawDecor(c,room,p);this.drawThresholds(c,room,p);for(let li=0;li<(room.lights||[]).length;li++){const l=room.lights[li],lf=this.perceptionSystem.lightFactor(li,fx,this.roomTime),r=l[2]*1.25,g=c.createRadialGradient(l[0],l[1],1,l[0],l[1],r);g.addColorStop(0,`rgba(255,178,87,${.30*lf})`);g.addColorStop(.25,`rgba(224,115,52,${.12*lf})`);g.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=g;c.fillRect(l[0]-r,l[1]-r,r*2,r*2);c.globalAlpha=lf;c.fillStyle='#ffd08a';c.fillRect(l[0]-1,l[1]-3,3,5);c.fillStyle='#ff8b45';c.fillRect(l[0],l[1]-4,1,2);c.globalAlpha=1;}this.drawPerceptionArchitecture(c,room,p,fx);for(const z of room.corruption||[]){const cg=c.createRadialGradient(z[0]+z[2]/2,z[1]+z[3]/2,2,z[0]+z[2]/2,z[1]+z[3]/2,Math.max(z[2],z[3]));cg.addColorStop(0,'rgba(102,32,113,.22)');cg.addColorStop(1,'rgba(21,5,27,0)');c.fillStyle=cg;c.fillRect(...z);}if(fx.warp){c.fillStyle=`rgba(63,22,72,${.025*fx.amount})`;for(let i=0;i<8;i++)c.fillRect(0,(i*23+(this.roomTime*9)%23)|0,INTERNAL_W,1);}c.font='7px Georgia,serif';c.fillStyle='rgba(240,222,197,.86)';c.fillText(`${room.area.toUpperCase()} · ${room.era}`,9,11);c.fillStyle='rgba(223,196,166,.65)';c.fillText(room.name.toUpperCase(),INTERNAL_W-8-c.measureText(room.name.toUpperCase()).width,11);}
  drawThresholds(c,room,p){c.save();c.fillStyle='#050405';c.strokeStyle=p.trim;const ex=room.exits||{};if(ex.left){c.fillRect(0,65,16,48);c.strokeRect(4,67,11,44);c.fillStyle='rgba(216,143,75,.12)';c.fillRect(7,72,4,34);}if(ex.right){c.fillStyle='#050405';c.fillRect(304,65,16,48);c.strokeRect(304,67,11,44);c.fillStyle='rgba(216,143,75,.12)';c.fillRect(309,72,4,34);}if(ex.up){c.fillStyle='#050405';c.fillRect(142,0,36,16);c.strokeRect(144,4,32,11);}if(ex.down){c.fillStyle='#050405';c.fillRect(142,164,36,16);c.strokeRect(144,164,32,11);}c.restore();}
  drawDecor(c,room,p){const d=room.decor;if(!d)return;c.save();c.fillStyle='#221a20';
    if(d==='library'||d==='archive'){for(const x of [34,78,224,268]){c.fillStyle='#4a3535';c.fillRect(x,28,14,106);for(let y=34;y<126;y+=12){c.fillStyle=(y/12)%2?'#8b6d55':'#6d5a4e';c.fillRect(x+2,y,10,3);}}}
    if(d==='dining'){c.fillStyle='#4b3433';c.fillRect(96,72,128,34);c.fillStyle='#806755';for(let x=106;x<216;x+=22)c.fillRect(x,76,12,3);}
    if(d==='garden'){c.fillStyle='#41513d';for(const [x,y] of [[70,55],[130,96],[226,58]]){c.fillRect(x,y,3,24);c.fillRect(x-6,y+4,15,5);c.fillRect(x-10,y+10,21,5);}c.strokeStyle='#53605d';for(let x=34;x<290;x+=32)c.strokeRect(x,24,26,116);}
    if(d==='chapel'){c.fillStyle='#4b3a3a';c.fillRect(140,34,40,28);c.fillStyle='#8f745b';c.fillRect(151,38,18,4);c.fillRect(158,32,4,24);for(const x of [82,198]){c.fillStyle='#3b3032';c.fillRect(x,90,44,10);}}
    if(d==='bedroom'||d==='guest'||d==='nursery'){c.fillStyle='#4b3b43';c.fillRect(60,52,82,36);c.fillStyle='#7f6c63';c.fillRect(64,56,74,13);c.fillStyle='#3d3237';c.fillRect(212,48,38,34);}
    if(d==='study'){c.fillStyle='#513b36';c.fillRect(184,72,82,28);c.fillStyle='#86705b';c.fillRect(190,75,70,4);c.fillStyle='#473237';c.fillRect(54,52,58,16);}
    if(d==='cellar'){for(const x of [58,114,182,238]){c.fillStyle='#3b302d';c.fillRect(x,46,28,88);for(let y=53;y<126;y+=12){c.fillStyle='#705044';c.fillRect(x+4,y,20,5);}}}
    if(d==='boiler'){c.fillStyle='#493b3a';c.fillRect(64,52,66,62);c.fillStyle='#79645b';c.fillRect(70,58,54,6);c.fillStyle='#3d4748';for(let x=150;x<274;x+=22)c.fillRect(x,28,5,104);}
    if(d==='vault'){for(let i=0;i<9;i++){const a=i/9*Math.PI*2,x=160+Math.cos(a)*78,y=88+Math.sin(a)*48;c.fillStyle=i===0?'#8c6a4b':'#3e3442';c.fillRect((x-5)|0,(y-7)|0,10,14);}c.strokeStyle='#79606e';c.strokeRect(118,46,84,84);}
    if(d==='mirror'){c.fillStyle='#58616a';c.fillRect(128,40,64,76);c.fillStyle='rgba(173,185,194,.18)';c.fillRect(134,46,52,64);}
    if(d==='root'){c.strokeStyle='#5b3c45';for(let i=0;i<11;i++){c.beginPath();c.moveTo(160,130);c.lineTo(70+seeded(i)*180,30+seeded(i+9)*90);c.stroke();}}
    if(d==='stairwell'){c.fillStyle='#4a3c3d';for(let i=0;i<7;i++)c.fillRect(70+i*22,130-i*12,70,7);}
    if(d==='gallery'){for(const x of [58,111,164,217]){c.strokeStyle='#795b52';c.strokeRect(x,34,24,40);c.fillStyle='#241b22';c.fillRect(x+4,39,16,28);}}
    if(d==='priory'||d==='cloister'){c.strokeStyle='#625c55';for(let x=42;x<286;x+=48){c.strokeRect(x,28,26,98);c.beginPath();c.moveTo(x,48);c.lineTo(x+13,32);c.lineTo(x+26,48);c.stroke();}}
    if(d==='infirmary'){for(const x of [48,128,208]){c.fillStyle='#4a3d39';c.fillRect(x,54,64,16);c.fillStyle='#76665d';c.fillRect(x+4,58,56,5);}}
    if(d==='apothecary'){for(const x of [52,106,236]){c.fillStyle='#493a35';c.fillRect(x,36,26,94);for(let y=44;y<120;y+=16){c.fillStyle='#806a4f';c.fillRect(x+4,y,18,5);}}}
    if(d==='ossuary'||d==='crypt'){for(let x=44;x<280;x+=38){c.fillStyle='#736b62';c.fillRect(x,58,14,8);c.fillRect(x+3,68,8,16);c.fillStyle='#3f3938';c.fillRect(x-4,88,22,6);}}
    if(d==='belfry'){c.strokeStyle='#75615d';c.lineWidth=2;c.strokeRect(126,24,68,46);c.beginPath();c.moveTo(160,24);c.lineTo(160,92);c.stroke();c.fillStyle='#5a4743';c.fillRect(104,118,112,10);c.lineWidth=1;}
    if(d==='salt'||d==='observatory'){c.fillStyle='#5d594d';for(let i=0;i<8;i++){const x=42+i*32,y=46+(i%3)*22;c.fillRect(x,y,18,4);c.fillStyle='#8b866c';c.fillRect(x+4,y-6,2,12);c.fillStyle='#5d594d';}c.strokeStyle='#81795e';c.beginPath();c.arc(160,84,42,0,Math.PI*2);c.stroke();}
    if(d==='cistern'){c.fillStyle='#28383b';c.fillRect(36,108,248,34);c.strokeStyle='#667271';for(let x=54;x<276;x+=44)c.strokeRect(x,38,28,66);}
    if(d==='bridge'){c.fillStyle='#4b4742';c.fillRect(72,92,176,18);c.strokeStyle='#777064';c.strokeRect(72,92,176,18);}
    if(d==='roman'){c.fillStyle='#514a43';for(const x of [62,116,190,244]){c.fillRect(x,42,14,84);c.fillStyle='#80776a';c.fillRect(x-5,38,24,7);c.fillStyle='#514a43';}}
    if(d==='theatre'){c.strokeStyle='#6e5654';for(let i=0;i<4;i++)c.strokeRect(70+i*18,48+i*12,180-i*36,70-i*24);c.fillStyle='#4e3938';c.fillRect(116,104,88,20);}
    c.restore();
  }
  drawInteractables(c,room,fx){const ngEcho=this.ngPlusEchoForRoom(room),items=ngEcho?[...(room.interact||[]),ngEcho]:(room.interact||[]);for(const it of items){if(it.once&&this.save.flags.includes(`seen:${it.id}`))continue;const near=Math.hypot((it.x+it.w/2)-(this.player.x+5),(it.y+it.h/2)-(this.player.y+7))<32;if(this.sigilBuffs.reveal<=0&&!this.perceptionSystem.objectVisible(it.id,fx,this.roomTime,near))continue;const pulse=.55+.35*Math.sin(this.roomTime*3+it.x*.1);c.save();c.globalAlpha=.22+.18*pulse;c.fillStyle=it.kind==='ngplus-echo'?'#a97bc7':'#d47a45';c.beginPath();c.arc(it.x+it.w/2,it.y+it.h/2,Math.max(8,it.w*.75),0,Math.PI*2);c.fill();c.globalAlpha=1;c.fillStyle='#171116';c.fillRect(it.x,it.y+Math.max(2,it.h-5),it.w,5);c.fillStyle=it.kind==='ngplus-echo'?'#c6a6e1':'#d59a63';c.fillRect(it.x+2,it.y+2,Math.max(2,it.w-4),2);c.fillStyle='#efe0c5';c.fillRect(it.x+Math.floor(it.w/2)-1,it.y,2,3);if(near){c.fillStyle='#f4e4c6';c.font='7px Georgia,serif';const label=`C · ${it.label.toUpperCase()}`;c.fillText(label,Math.max(6,Math.min(314-c.measureText(label).width,it.x-8)),it.y-5);}c.restore();}}
  drawPlayer(c){const p=this.player,x=p.x-5,y=p.y-10,step=Math.floor(this.roomTime*8)%2;c.save();c.fillStyle='rgba(0,0,0,.55)';c.beginPath();c.ellipse(p.x+5,p.y+p.h+3,10,4,0,0,Math.PI*2);c.fill();const hurt=p.hitFlash>0;c.fillStyle=hurt?'#f6ddce':'#3a3035';c.fillRect(x+6,y+9,9,12);c.fillStyle='#1a171b';c.fillRect(x+5,y+13,11,9);c.fillStyle='#6f2227';c.fillRect(x+4,y+12,4,12);c.fillStyle='#8d3031';c.fillRect(x+7,y+17,8,7);c.fillStyle='#bcb1a1';c.fillRect(x+8,y+3,6,6);c.fillStyle='#342a2c';c.fillRect(x+7,y+2,8,3);c.fillStyle='#0b0a0c';c.fillRect(x+8,y+4,2,1);c.fillRect(x+12,y+4,2,1);c.fillStyle='#625a57';c.fillRect(x+6,y+9,2,9);c.fillRect(x+14,y+10,2,8);c.fillStyle='#171417';c.fillRect(x+7,y+21+(step?1:0),3,5);c.fillRect(x+12,y+21+(step?0:1),3,5);c.strokeStyle='#d0c2aa';if(p.facing==='left'){c.beginPath();c.moveTo(x+7,y+14);c.lineTo(x-3,y+17);c.stroke();}else if(p.facing==='right'){c.beginPath();c.moveTo(x+15,y+14);c.lineTo(x+26,y+17);c.stroke();}else if(p.facing==='up'){c.beginPath();c.moveTo(x+14,y+10);c.lineTo(x+17,y-2);c.stroke();}else{c.beginPath();c.moveTo(x+8,y+17);c.lineTo(x+5,y+29);c.stroke();}if(this.guard){c.strokeStyle=this.parryTimer>0?'#f0c27c':'#9d8e78';c.lineWidth=2;c.beginPath();c.arc(p.x+5,p.y+8,11,-1.2,1.2);c.stroke();}if(this.charging){const q=this.weapon.chargeMax?Math.min(1,this.chargeTime/this.weapon.chargeMax):0;c.strokeStyle=`rgba(216,103,67,${.45+.4*q})`;c.strokeRect(x-2-q*2,y-2-q*2,26+q*4,32+q*4);}c.restore();}
  drawEnemy(c,e,fx){let visible=true;if(e.boss&&this.bossPhase===3&&this.bossVulnerable<=0)visible=(Math.floor(this.roomTime*5)%4===0)||fx.tier>=3;if(!visible)return;const prof=e.boss?(BOSS_PROFILES[e.type]||{}):null,accent=e.boss?(prof.accent||'#9c473f'):e.family==='Pale Ones'?'#a9a69b':e.family==='Witness'?'#71627a':e.family==='Ashborn'?'#8f5137':e.family==='Cultborn'?'#76503d':'#5d4653';const vw=e.boss?Math.max(30,e.w*2.1):Math.max(17,e.w*1.35),vh=e.boss?Math.max(38,e.h*2.2):Math.max(24,e.h*1.5),x=e.x+e.w/2-vw/2,y=e.y+e.h-vh;c.save();c.fillStyle='rgba(0,0,0,.62)';c.beginPath();c.ellipse(e.x+e.w/2,e.y+e.h+3,vw*.42,Math.max(3,vh*.1),0,0,Math.PI*2);c.fill();c.fillStyle=e.hitFlash>0?'#ead4c5':'#111014';c.fillRect(x+vw*.28,y+vh*.22,vw*.44,vh*.64);c.fillStyle=accent;c.globalAlpha=e.boss?.92:.78;c.fillRect(x+vw*.18,y+vh*.43,vw*.64,vh*.42);c.globalAlpha=1;c.fillStyle='#0b090c';c.fillRect(x+vw*.08,y+vh*.74,vw*.84,vh*.16);c.fillStyle=e.boss?'#c6b39b':'#887d74';c.fillRect(x+vw*.34,y+vh*.08,vw*.32,vh*.20);c.fillStyle='#0a0709';c.fillRect(x+vw*.37,y+vh*.13,vw*.08,2);c.fillRect(x+vw*.56,y+vh*.13,vw*.08,2);c.fillStyle=e.boss?'#e35d3e':'#b05b51';c.fillRect(x+vw*.40,y+vh*.14,1,1);c.fillRect(x+vw*.59,y+vh*.14,1,1);if(e.boss){c.strokeStyle=accent;c.lineWidth=2;c.beginPath();c.moveTo(x+vw*.34,y+vh*.1);c.lineTo(x+vw*.20,y-3);c.moveTo(x+vw*.66,y+vh*.1);c.lineTo(x+vw*.80,y-3);c.stroke();c.fillStyle='rgba(212,86,57,.22)';c.beginPath();c.arc(e.x+e.w/2,e.y+e.h/2,vw*.65,0,Math.PI*2);c.fill();}if(e.pendingAttack){const t=e.windupMax?1-e.windup/e.windupMax:1;c.strokeStyle=t>.65?'#ff9b62':'#a76052';c.lineWidth=t>.65?2:1;c.strokeRect(x-3,y-3,vw+6,vh+6);}if(e.stagger>0){c.strokeStyle='#e2bc72';c.strokeRect(x-5,y-5,vw+10,vh+10);}if(e.bound>0){c.strokeStyle='#ab7fc0';c.strokeRect(x-2,y-2,vw+4,vh+4);}if(e.branded>0){c.strokeStyle='#d06e72';c.strokeRect(x-4,y-4,vw+8,vh+8);}if(e.boss&&this.bossVulnerable>0){c.strokeStyle='#f2b36f';c.strokeRect(x-2,y-2,vw+4,vh+4);}c.restore();}
  drawMap(c){
    c.fillStyle='rgba(5,4,7,.93)';c.fillRect(12,12,296,156);c.strokeStyle='#70515f';c.strokeRect(12.5,12.5,295,155);c.font='8px monospace';c.fillStyle='#e5d7ca';c.fillText('BLACKTHORN MANOR · RECOVERED SURVEY',25,27);c.font='6px monospace';c.fillStyle='#958681';c.fillText('M / ESC · CLOSE   ■ CURRENT   □ DISCOVERED',25,38);
    const manorRooms=Object.values(ROOMS).filter(r=>r.tone==='manor'&&Number.isFinite(r.floor)&&r.id!=='manor-gallery');
    const aliases=new Set(this.save.rooms.map(id=>this.resolveRoomId(id)));aliases.add(this.resolveRoomId(this.save.room));
    for(let fi=0;fi<MANOR_FLOORS.length;fi++){const fl=MANOR_FLOORS[fi],top=48+fi*39;c.fillStyle='#a47768';c.fillText(fl.label,25,top);const rooms=manorRooms.filter(r=>r.floor===fl.id&&aliases.has(r.id));for(const r of rooms){const x=58+(r.mapX+1)*43,y=top-10+r.mapY*15;const current=r.id===this.resolveRoomId(this.save.room);c.fillStyle=current?'#a46e5c':'#2b222a';c.fillRect(x,y,36,11);c.strokeStyle=current?'#e5c2a7':'#6a5660';c.strokeRect(x+.5,y+.5,35,10);c.fillStyle=current?'#160d0e':'#d0c0b6';c.font='5px monospace';const t=r.name.toUpperCase().replace(' · ALTERED','').slice(0,7);c.fillText(t,x+2,y+7);}}
    c.fillStyle='#8b7a75';c.font='6px monospace';c.fillText(`${Math.min(23,aliases.size)} MANOR SPACES REMEMBERED`,25,160);
  }
  drawPhantom(c,p,fx){if(p.type==='shadow'){c.globalAlpha=.09+.08*fx.amount;c.fillStyle='#09070d';c.fillRect(p.x,p.y,p.w||9,p.h||20);c.fillRect(p.x-4,p.y+(p.h||20)-3,(p.w||9)+8,3);}else{c.globalAlpha=.28+.18*fx.amount;c.fillStyle='#b6a5c8';c.fillRect(p.x+2,p.y,p.w-4,p.h);c.fillStyle='#17131c';c.fillRect(p.x,p.y+5,p.w,p.h-5);c.fillStyle='#d0c3dc';c.fillRect(p.x+3,p.y+5,2,2);c.fillRect(p.x+p.w-5,p.y+5,2,2);}c.globalAlpha=1;}
  drawPerceptionArchitecture(c,room,p,fx){
    if(fx.roomShift){c.save();c.globalAlpha=.12+.08*fx.amount;c.strokeStyle='#8b6c91';const drift=Math.round(Math.sin(this.roomTime*1.7)*4);for(let i=0;i<3;i++)c.strokeRect(42+i*78+drift,34+i*17,54,38);c.fillStyle='#4a344d';c.fillRect(112+drift,118,96,5);c.restore();}
    if(fx.doorVeil&&Math.sin(this.roomTime*1.35+room.name.length)>.05){const dirs=Object.keys(room.exits||{});if(dirs.length){const dir=dirs[(room.name.length+Math.floor(this.roomTime/4))%dirs.length];c.save();c.globalAlpha=.72*fx.amount;c.fillStyle=p.wall;c.strokeStyle=p.trim;if(dir==='up'||dir==='down'){const y=dir==='up'?0:164;c.fillRect(142,y,36,16);c.strokeRect(142.5,y+.5,35,15);}else{const x=dir==='left'?0:304;c.fillRect(x,65,16,47);c.strokeRect(x+.5,65.5,15,46);}c.restore();}}
  }
  drawPerceptionEcho(c,fx){if(!fx.echoes||!this.echoes.length)return;const e=this.echoes[this.echoes.length-1];c.save();c.globalAlpha=Math.min(.62,e.life*.34)*fx.amount;c.font='6px monospace';c.fillStyle='#cbbbd3';const text=e.text.slice(0,46);c.fillText(text,12,154);c.restore();}
  drawFakeGlitches(c,fx){if(!fx.fakeGlitch)return;c.save();for(const g of this.fakeGlitches){c.globalAlpha=Math.min(.7,g.life*3)*fx.amount;c.fillStyle='#7d657f';c.fillRect(g.dx,g.y,INTERNAL_W-g.dx*2,g.h);c.fillStyle='#160d19';c.fillRect(30+g.dx,g.y+1,120,g.h>3?2:1);}if(this.fakeGlitches.length&&fx.tier>=4){c.globalAlpha=.45*fx.amount;c.font='6px monospace';c.fillStyle='#d2c4d8';c.fillText('MEMORY SIGNAL // LOCAL FICTION',10,22);}c.restore();}
  drawProjectile(c,p){const delayed=(p.delay||0)>0;c.save();if(delayed){c.globalAlpha=.35;c.strokeStyle='#e0b375';c.strokeRect(p.x-4,p.y-4,8,8);c.restore();return;}const bossCols={'bell-ring':'#bb554f','salt-star':'#d2a85f','salt-comet':'#e6c77f','census-axis':'#a58b70','census-entry':'#c2aa8d','mirror-left':'#a679b4','mirror-right':'#725380','tenant-threshold':'#b76b4e','company-volley':'#8a8072','frequency-band':'#5f99a2','missing-frame':'#8a65a2','missing-cut':'#cf7bbb','unremembered-ring':'#c14369','relation-cut':'#e16483'};const col=p.hostile?(bossCols[p.kind]||'#bd5a64'):'#e3b764';c.globalAlpha=.28;c.fillStyle=col;c.beginPath();c.arc(p.x,p.y,5,0,Math.PI*2);c.fill();c.globalAlpha=1;c.fillStyle=col;c.fillRect(p.x-2,p.y-2,4,4);c.fillStyle='#fff0c2';c.fillRect(p.x-1,p.y-1,2,2);c.restore();}
  drawParticles(c){for(const p of this.particles){c.globalAlpha=Math.min(1,p.life*2);if(p.text){c.fillStyle='#ead7b9';c.font='7px monospace';c.fillText(p.text,p.x,p.y);}else{c.fillStyle='#b99878';c.fillRect(p.x|0,p.y|0,2,2);}}c.globalAlpha=1;}
  drawVignette(c,room,fx){const darkness=room.tone==='manor'?.25:.34+fx.tier*.03;const g=c.createRadialGradient(160,98,42,160,98,180);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.72,'rgba(0,0,0,.05)');g.addColorStop(1,`rgba(0,0,0,${darkness})`);c.fillStyle=g;c.fillRect(0,0,320,180);c.fillStyle='rgba(120,42,31,.06)';c.fillRect(0,0,320,3);c.fillRect(0,177,320,3);if(fx.heavy){c.fillStyle=`rgba(53,15,58,${.07*fx.amount})`;c.fillRect(0,0,320,180);}}
}
