const CACHE='blackthorn404-v1.1.3-ios-attack-hotfix';
const SHELL=['./','./index.html','./css/app.css?v=1.1.1','./js/bundle.js?v=1.1.1','./manifest.webmanifest?v=1.1.1','./assets/icons/icon.svg','./assets/icons/icon-192.png','./assets/icons/icon-512.png','./assets/art/title_hero.jpg','./assets/art/scene_manor.png','./assets/art/scene_medieval.png','./assets/art/scene_ancient.png','./assets/art/scene_modern.png','./assets/art/scene_boss.png','./assets/art/scene_void.png'];
const OPTIONAL=[];
const CORE_RE=/\/(?:js\/bundle\.js|css\/app\.css|manifest\.webmanifest)$/;
const IOS_ATTACK_PATCH=`\n;(()=>{if(window.__BT404_IOS_ATTACK_PATCH__)return;window.__BT404_IOS_ATTACK_PATCH__=true;const bind=()=>{const b=document.querySelector('[data-control="attack"]');if(!b||b.dataset.iosAttackPatch)return;b.dataset.iosAttackPatch='1';let active=false;const start=e=>{if(e.cancelable)e.preventDefault();active=true;b.classList.add('pressed');const s=window.__BT404__;s?.audio?.ensure?.();s?.engine?.setControl('attack',true);};const end=e=>{if(e.cancelable)e.preventDefault();if(!active)return;active=false;b.classList.remove('pressed');window.__BT404__?.engine?.setControl('attack',false);};b.addEventListener('touchstart',start,{passive:false,capture:true});b.addEventListener('touchend',end,{passive:false,capture:true});b.addEventListener('touchcancel',end,{passive:false,capture:true});};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();})();\n`;
async function networkCore(request,url){const res=await fetch(request,{cache:'no-store'});if(!res||!res.ok)return res;if(/\/js\/bundle\.js$/.test(url.pathname)){const text=await res.text();const patched=new Response(text+IOS_ATTACK_PATCH,{status:res.status,statusText:res.statusText,headers:new Headers(res.headers)});patched.headers.set('content-type','application/javascript; charset=utf-8');const c=await caches.open(CACHE);await c.put(request,patched.clone());return patched;}const c=await caches.open(CACHE);await c.put(request,res.clone());return res;}
self.addEventListener('install',event=>event.waitUntil((async()=>{const c=await caches.open(CACHE);await c.addAll(SHELL);await Promise.allSettled(OPTIONAL.map(x=>c.add(x)));await self.skipWaiting();})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('blackthorn404-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();})()));
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==location.origin)return;if(event.request.mode==='navigate'){event.respondWith((async()=>{try{const res=await fetch(event.request,{cache:'no-store'});if(res&&res.ok){const c=await caches.open(CACHE);await c.put('./index.html',res.clone());}return res;}catch{return (await caches.match('./index.html'))||(await caches.match('./'));}})());return;}if(CORE_RE.test(url.pathname)){event.respondWith((async()=>{try{return await networkCore(event.request,url);}catch{return (await caches.match(event.request))||Response.error();}})());return;}event.respondWith((async()=>{const cached=await caches.match(event.request);const refresh=fetch(event.request).then(async res=>{if(res&&res.ok){const c=await caches.open(CACHE);await c.put(event.request,res.clone());}return res;}).catch(()=>null);if(cached){event.waitUntil(refresh);return cached;}return (await refresh)||Response.error();})());});
